//@version=6
strategy("n2-member-9-literal", initial_capital=74754.84878043355, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 5, 23, 23, 30) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=29.7211)
if time == timestamp("UTC", 2025, 5, 24, 0, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
plot(math.floor(strategy.equity / close / 0.0001) * 0.0001, "source-size")
