//@version=6
strategy("pf-12b-e1-entry-only", initial_capital=712818.0281, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true, pyramiding=0)
if time == timestamp("UTC", 2025, 9, 16, 20, 30)
    strategy.entry("S", strategy.short, qty=600000.0)
if time == timestamp("UTC", 2025, 9, 16, 20, 45)
    strategy.entry("L", strategy.long, qty=599851.03)
if time == timestamp("UTC", 2025, 9, 16, 21, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
