//@version=6
strategy("n34-c1-gapstop-fee-slip", initial_capital=7745, commission_type=strategy.commission.percent, commission_value=0.04, slippage=1, margin_long=100, margin_short=100)
if time == timestamp("UTC", 2025, 7, 8, 19, 30)
    strategy.entry("Short", strategy.short, qty=658)
    strategy.exit("SE", from_entry="Short", stop=11.75)
if time == timestamp("UTC", 2025, 7, 9, 14, 0)
    strategy.close_all()
