//@version=6
strategy("N1 eth-flat-m100-ulp-above", initial_capital=8362.1728850000018, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2025, 5, 6, 12, 0)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################")
    strategy.entry("Turn", strategy.long, comment=witness)
if time == timestamp("UTC", 2025, 5, 6, 12, 30)
    strategy.close_all(comment="SENSOR|" + witness)
