//@version=6
strategy("pf-16b-s16-gaplim", initial_capital=10389.93902, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 12, 31, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=3414.03, limit=2968.14)
if time == timestamp("UTC", 2025, 12, 31, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
