//@version=6
strategy("n5-21-pending",initial_capital=500000,pyramiding=10,margin_long=0,margin_short=0,close_entries_rule="FIFO",process_orders_on_close=true)
if time == timestamp("UTC",2025,05,21,14,45,00)
    strategy.entry("S2",strategy.short,qty=1.9939,limit=2608.87)
    strategy.exit("X2",from_entry="S2",limit=2580.44,stop=2608.87)
if time == timestamp("UTC",2025,05,22,12,00,00)
    strategy.close_all()
