//@version=6
strategy("pxside-rlp-stp-opp-nc", overlay=true, initial_capital=1000000, default_qty_type=strategy.fixed, default_qty_value=1, calc_on_order_fills=false, process_orders_on_close=false)
hh = ta.highest(high, 10)
ll = ta.lowest(low, 10)
var float lvl = na
if strategy.position_size == 0
    lvl := na
    strategy.cancel("S")
    strategy.entry("L", strategy.long, qty=1)
else if strategy.position_size > 0
    strategy.entry("S", strategy.short, qty=1, stop=1.0)
    strategy.exit("X", profit=5)
