//@version=6
strategy("n12-c1-a4-exp-short-s1-gapup1", initial_capital=3710.745001, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=1, process_orders_on_close=false, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 5, 20, 16, 45) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=1.5)
if time == timestamp("UTC", 2025, 5, 20, 17, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
