//@version=6
strategy("n2cmfeesizemm0d000020", initial_capital=97096.02706588642, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 4, 12, 23, 0)
    strategy.entry("after", strategy.short)
if time == timestamp("UTC", 2025, 4, 13, 1, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "position")
