//@version=6
strategy("xk17-member-replica",initial_capital=5000,pyramiding=3,margin_long=0,margin_short=0,close_entries_rule="FIFO",commission_type=strategy.commission.percent,commission_value=0.04,slippage=3,process_orders_on_close=true)
fe = 3836.959
var bool be = false
if time == timestamp("UTC",2025,10,31,00,45,00)
    strategy.entry("L1",strategy.long,qty=1.5217,limit=fe)
if time == timestamp("UTC",2025,10,31,17,15,00)
    strategy.entry("L2",strategy.long,qty=1.5213,limit=3804.3448485)
if time >= timestamp("UTC",2025,10,31,01,00,00) and time <= timestamp("UTC",2025,10,31,20,00,00)
    if not be and close >= fe * 1.01
        be := true
    sl = be ? 3846.5513975 : (time >= timestamp("UTC",2025,10,31,17,15,00) ? 3728.25795 : 3760.21982)
    strategy.exit("xL1",from_entry="L1",limit=3990.43736,stop=sl)
    if time >= timestamp("UTC",2025,10,31,17,15,00)
        strategy.exit("xL2",from_entry="L2",limit=3990.43736,stop=sl)
if time == timestamp("UTC",2025,10,31,20,00,00)
    strategy.close_all(comment="EOD flatten")
