//@version=6
strategy("N6R declined-reissue-stop", overlay=true, initial_capital=85053.7, default_qty_type=strategy.percent_of_equity, default_qty_value=100, calc_on_order_fills=false, process_orders_on_close=false, pyramiding=0, margin_long=100, margin_short=100, commission_value=0, slippage=0)
if time == timestamp("UTC",2025,5,28,17,0)
    strategy.entry('BUY', strategy.long)
if time == timestamp("UTC",2025,5,28,19,30)
    strategy.entry('SELL', strategy.short)
if strategy.position_size > 0
    strategy.exit('TP BUY', from_entry = 'BUY', limit = 2681.5, qty_percent = 50)
    strategy.exit('SL BUY', from_entry = 'BUY', stop = 2614.0, qty_percent = 50)
