// Generated by scripts/check_run_failure_codes.py --write-registry from
// docker/run_failure_codes.json. Do not edit: edit the catalog and
// regenerate.

#pragma once

#include <cstdint>

namespace pineforge {

// The closed run-failure vocabulary (docker/run_failure_codes.json),
// in catalog order. `none` is no failure. The numbers are not on any
// wire: the C getters answer with the names.
enum class RunFailureCode : std::uint16_t {
    none = 0,
    chart_bars_rejected = 1,
    chart_bars_unreadable = 2,
    engine_command_value_invalid = 3,
    engine_invariant = 4,
    engine_unclassified_error = 5,
    harness_internal_error = 6,
    lot_grid_rejected = 7,
    no_data_request = 8,
    other_symbol_feed_missing = 9,
    other_symbol_request = 10,
    out_of_memory = 11,
    outputs_limit = 12,
    outputs_rejected = 13,
    pine_array_error = 14,
    pine_invalid_argument = 15,
    pine_matrix_error = 16,
    pine_na_reference = 17,
    pine_runtime_limit = 18,
    pine_string_error = 19,
    recalc_cap = 20,
    recorded_request_missing = 21,
    recorded_request_refused = 22,
    report_platform_unavailable = 23,
    report_post_execution_failed = 24,
    report_result_invalid = 25,
    report_shape_request_invalid = 26,
    report_shape_unsupported = 27,
    request_symbol_invalid = 28,
    request_timeframe_invalid = 29,
    request_timeframe_unsupported = 30,
    request_unsupported = 31,
    results_digest_unsupported = 32,
    run_aborted = 33,
    run_mode_unsupported = 34,
    run_options_rejected = 35,
    run_request_invalid = 36,
    security_feed_refused = 37,
    setting_rejected = 38,
    setting_unsupported = 39,
    strategy_create_failed = 40,
    strategy_library_incompatible = 41,
    strategy_runtime_error = 42,
    strategy_settings_rejected = 43,
    strategy_value_invalid = 44,
    stream_input_rejected = 45,
    symbol_feeds_refused = 46,
    symbol_metadata_rejected = 47,
    syminfo_unreadable = 48,
    window_boundary_unaligned = 49,
    window_calendar_unsupported = 50,
    window_feed_identity_changed = 51,
    window_feed_range_invalid = 52,
    window_input_cap_exceeded = 53,
    window_legacy_flag_conflict = 54,
    window_lineage_mismatch = 55,
    window_mode_unsupported = 56,
    window_no_observations = 57,
    window_preroll_out_of_range = 58,
    window_prestart_fill = 59,
    window_prestart_state_violation = 60,
    window_pruner_unsupported = 61,
    window_range_invalid = 62,
    window_report_mismatch = 63,
    window_request_invalid = 64,
};

inline constexpr std::uint16_t kRunFailureCodeCount = 65;

}  // namespace pineforge
