// Generated by scripts/check_run_failure_codes.py --write-registry from
// docker/run_failure_codes.json. Do not edit: edit the catalog and
// regenerate.

#pragma once

#include <cstdint>

namespace pineforge {

// The closed run-failure vocabulary (docker/run_failure_codes.json),
// in catalog order. `none` is no failure. The numbers are not on any
// wire: the C getters answer with the names.
enum class RunFailureCode : std::uint16_t {
    none = 0,
    chart_bars_rejected = 1,
    chart_bars_unreadable = 2,
    engine_invariant = 3,
    engine_unclassified_error = 4,
    harness_internal_error = 5,
    lot_grid_rejected = 6,
    no_data_request = 7,
    other_symbol_feed_missing = 8,
    other_symbol_request = 9,
    out_of_memory = 10,
    outputs_limit = 11,
    outputs_rejected = 12,
    pine_array_error = 13,
    pine_invalid_argument = 14,
    pine_matrix_error = 15,
    pine_na_reference = 16,
    pine_runtime_limit = 17,
    pine_string_error = 18,
    recalc_cap = 19,
    recorded_request_missing = 20,
    recorded_request_refused = 21,
    request_symbol_invalid = 22,
    request_timeframe_invalid = 23,
    request_timeframe_unsupported = 24,
    request_unsupported = 25,
    run_aborted = 26,
    run_mode_unsupported = 27,
    run_options_rejected = 28,
    run_request_invalid = 29,
    security_feed_refused = 30,
    setting_rejected = 31,
    setting_unsupported = 32,
    strategy_create_failed = 33,
    strategy_library_incompatible = 34,
    strategy_runtime_error = 35,
    strategy_settings_rejected = 36,
    stream_input_rejected = 37,
    symbol_feeds_refused = 38,
    symbol_metadata_rejected = 39,
    syminfo_unreadable = 40,
};

inline constexpr std::uint16_t kRunFailureCodeCount = 41;

}  // namespace pineforge
