// Generated by scripts/check_run_failure_codes.py --write-registry from
// docker/run_failure_codes.json. Do not edit: edit the catalog and
// regenerate.

#pragma once

#include <cstdint>

namespace pineforge {

// The closed run-failure vocabulary (docker/run_failure_codes.json),
// in catalog order. `none` is no failure. The numbers are not on any
// wire: the C getters answer with the names.
enum class RunFailureCode : std::uint16_t {
    none = 0,
    chart_bars_rejected = 1,
    chart_bars_unreadable = 2,
    engine_invariant = 3,
    engine_unclassified_error = 4,
    harness_internal_error = 5,
    lot_grid_rejected = 6,
    no_data_request = 7,
    other_symbol_feed_missing = 8,
    other_symbol_request = 9,
    out_of_memory = 10,
    pine_array_error = 11,
    pine_invalid_argument = 12,
    pine_matrix_error = 13,
    pine_na_reference = 14,
    pine_runtime_limit = 15,
    pine_string_error = 16,
    recalc_cap = 17,
    recorded_request_missing = 18,
    recorded_request_refused = 19,
    request_symbol_invalid = 20,
    request_timeframe_invalid = 21,
    request_timeframe_unsupported = 22,
    request_unsupported = 23,
    run_aborted = 24,
    run_mode_unsupported = 25,
    run_options_rejected = 26,
    run_request_invalid = 27,
    security_feed_refused = 28,
    setting_rejected = 29,
    setting_unsupported = 30,
    strategy_create_failed = 31,
    strategy_library_incompatible = 32,
    strategy_runtime_error = 33,
    strategy_settings_rejected = 34,
    stream_input_rejected = 35,
    symbol_feeds_refused = 36,
    symbol_metadata_rejected = 37,
    syminfo_unreadable = 38,
};

inline constexpr std::uint16_t kRunFailureCodeCount = 39;

}  // namespace pineforge
