//@version=6
strategy("pf-n2s-f2-whole-share-L", initial_capital=6192.840000000001, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 10, 2, 13, 45)
    strategy.entry("S", strategy.short, qty=500.0)
if time == timestamp("UTC", 2025, 10, 2, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
