//@version=6
strategy("xk41-global-exit-first",initial_capital=100000,pyramiding=3,margin_long=0,margin_short=0,close_entries_rule="FIFO",process_orders_on_close=true)
if time == timestamp("UTC",2025,10,31,17,15,00)
    strategy.exit("xG",stop=3750,limit=3990.44)
    strategy.entry("L2",strategy.long,qty=1.5213,limit=3804.3448485)
if time == timestamp("UTC",2025,11,03,20,00,00)
    strategy.close_all()
