//@version=6
strategy("n2-short-s0", initial_capital=10646.800094883001, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 4, 8, 13, 45) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=6.7883)
if time == timestamp("UTC", 2025, 4, 8, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
