//@version=6
strategy("pf-n2s-r05-0209", initial_capital=7362.799300000004, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2026, 2, 9, 14, 30)
    strategy.entry("S", strategy.short, qty=540.0)
if time == timestamp("UTC", 2026, 2, 9, 18, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
