//@version=6
strategy("pf-n2s-r12-gap-1017", initial_capital=44844.53903007983, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 10, 17, 20, 45)
    strategy.entry("S", strategy.short, qty=38490.17)
if time == timestamp("UTC", 2025, 10, 19, 21, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
