//@version=6
strategy("pxsame2-L-pl-rlim-nc", overlay=true, initial_capital=1000000, default_qty_type=strategy.fixed, default_qty_value=1, pyramiding=2, calc_on_order_fills=false, process_orders_on_close=false)
var bool placed = false
if strategy.position_size == 0
    strategy.cancel("A")
    placed := false
    strategy.entry("L", strategy.long, qty=1)
else if strategy.position_size > 0
    if not placed
        strategy.entry("A", strategy.long, qty=1, limit=strategy.position_avg_price - 0.02)
        placed := true
    strategy.exit("X", profit=4, loss=6)
