//@version=6
strategy("N1 willow-history-k0-after", initial_capital=74843.759999999995, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2026, 3, 18, 18, 15)
    strategy.entry("Seed", strategy.long, qty=6299)
if time == timestamp("UTC", 2026, 3, 19, 16, 30)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################") + ";D=" + str.tostring(strategy.default_entry_qty(math.round_to_mintick(close)), "#.################")
    strategy.entry("Turn", strategy.short, comment=witness)
    strategy.close("Seed")
if time == timestamp("UTC", 2026, 3, 19, 17, 0)
    strategy.close_all(comment="SENSOR|" + witness)
