//@version=6
strategy("n2-short-m50-s5", initial_capital=5323.569670087751, margin_long=50, margin_short=50, commission_type=strategy.commission.percent, commission_value=0.05, slippage=5, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 4, 8, 13, 45) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=6.7883)
if time == timestamp("UTC", 2025, 4, 8, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
