//@version=6
strategy("px-n789 n7 n7-d5-computed-split", overlay = true, initial_capital = 100000, default_qty_type = strategy.fixed, default_qty_value = 1, pyramiding = 1, process_orders_on_close = true, margin_long = 1, margin_short = 1)
if time == timestamp("UTC", 2025, 9, 5, 13, 30)
    float r = (11.91 + syminfo.mintick * 15) - 11.74
    strategy.entry("S", strategy.short, qty = (strategy.equity * 1.0 / 100.0) / r)
    strategy.exit("TP1", "S", qty_percent = 50, limit = 10.0)
    strategy.exit("MAIN", "S", stop = 12.06)
if time == timestamp("UTC", 2025, 10, 15, 13, 30)
    strategy.close_all(comment = "X")
