//@version=6
strategy("pf-n2s-r16-adm-0502-ok", initial_capital=9083.666855171503, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 5, 2, 0, 15)
    strategy.entry("L", strategy.long, qty=4.9204)
if time == timestamp("UTC", 2025, 5, 2, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
