//@version=6
strategy("pf-n2s-f5-owed-dropped-F", initial_capital=6558.0225, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 12, 9, 18, 30)
    strategy.entry("S", strategy.short, qty=500.0)
if time == timestamp("UTC", 2025, 12, 9, 19, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
