//@version=6
strategy("n2b-delta-coof-off-m1n", initial_capital=27.359999999, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=2, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 12, 15, 20, 30) and strategy.position_size == 0
    strategy.entry("probe", strategy.long, qty=2.0)
if time == timestamp("UTC", 2025, 12, 15, 20, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
