// test_ta_rma_warmup — fixed-fixture correctness for RMA + RSI warmup.
//
// Anchors the RMA / RSI implementation to the *exact* Pine reference
// formula:
//
//   rma := na(rma[1]) ? sma(src, length) : (src + (length - 1) * rma[1]) / length
//
// Two implementations are mathematically equivalent over real numbers:
//
//   (A) (src + (length - 1) * rma[1]) / length         <-- Pine ref
//   (B) alpha * src + (1 - alpha) * rma[1], alpha=1/L  <-- algebraic rewrite
//
// In IEEE-754 double-precision arithmetic they differ by 1-3 ULP per bar
// because the rounding-mode-sensitive operation order is different. Form
// (A) is what TradingView's runtime evaluates, so we use (A) in the
// engine and lock it down here. Reference values were generated by an
// independent Python implementation following the same expression order
// and confirmed by hand-computation on the seed bar.
//
// Coverage:
//   * RMA(14) seed bar value (SMA of first 14 inputs / 14).
//   * RMA(14) first smoothing iteration (bar 14).
//   * RMA(14) deep into smoothing (bar 29).
//   * RSI(14) seed bar (Pine spec: first non-NA at bar `length` = 14
//     using close-to-close changes from bars 1..14, with the first valid
//     change at bar 1).
//   * RSI(14) several bars deep into smoothing.
//   * RSI(14) limit cases:
//        - all-up sequence collapses to 100 (rma_down == 0 short-circuit).
//        - all-down sequence collapses to 0 (rma_up == 0).
//
// The fixture is small (30 bars) and fully reproducible: the close
// series, expected RMA values, and expected RSI values are all hard-
// coded below. If you intentionally change the RMA / RSI implementation
// in src/ta_moving_averages.cpp or src/ta_oscillators.cpp this test will
// catch the per-bar ULP drift immediately.

#include <pineforge/ta.hpp>
#include <pineforge/na.hpp>

#include <cmath>
#include <cstdio>
#include <vector>

using namespace pineforge;

static int tests_passed = 0;
static int tests_failed = 0;

// Bit-exact equality is the right check for IEEE-754 reference values:
// either we match the Pine formula to the last bit, or we don't. ULP
// tolerance would silently re-introduce the algebraic-rewrite drift.
static bool exact_eq(double a, double b) {
    if (is_na(a) && is_na(b)) return true;
    if (is_na(a) || is_na(b)) return false;
    return a == b;
}

#define CHECK_EXACT(actual, expected, tag) do { \
    double _a = (actual); \
    double _e = (expected); \
    if (!exact_eq(_a, _e)) { \
        std::printf("FAIL: %s (line %d): got %.17g expected %.17g (diff=%.17g)\n", \
                    tag, __LINE__, _a, _e, _a - _e); \
        ++tests_failed; \
    } else { \
        ++tests_passed; \
    } \
} while (0)

#define CHECK_NA(actual, tag) do { \
    if (!is_na(actual)) { \
        std::printf("FAIL: %s (line %d): got %.17g expected NA\n", tag, __LINE__, (actual)); \
        ++tests_failed; \
    } else { \
        ++tests_passed; \
    } \
} while (0)

// --------------------------------------------------------------------
// Fixture: 30-bar increasing-then-decreasing close series.
// --------------------------------------------------------------------

static const std::vector<double> kCloses = {
    10.0, 11.0, 12.0, 11.5, 12.5, 13.0, 14.0, 13.5, 14.5, 15.0,
    16.0, 15.5, 14.0, 13.5, 13.0, 12.5, 12.0, 11.5, 11.0, 10.5,
    10.0,  9.5,  9.0,  8.5,  8.0,  7.5,  7.0,  6.5,  6.0,  5.5,
};

// Expected RMA(14) values, generated by:
//   pine_rma(xs, 14) where rma_i = (x_i + 13 * rma_{i-1}) / 14
//   seeded by SMA of first 14 values: sum(xs[0..13]) / 14
//   = (10+11+12+11.5+12.5+13+14+13.5+14.5+15+16+15.5+14+13.5)/14
//   = 186.0 / 14 = 13.285714285714286 (exact double).
static const std::vector<double> kRMA14_expected = {
    // bars 0..12: NA (warmup)
    // bar 13: seed
    13.285714285714286,
    // bar 14: (13.0 + 13 * 13.285714285714286) / 14
    13.26530612244898,
    // bar 15
    13.210641399416911,
    // bar 16
    13.124167013744273,
    // bar 17
    13.008155084191111,
    // bar 18
    12.864715435320319,
    // bar 19
    12.695807189940297,
    // bar 20
    12.503249533515989,
    // bar 21
    12.288731709693419,
    // bar 22
    12.053822301858174,
    // bar 23
    11.799977851725448,
    // bar 24
    11.528550862316488,
    // bar 25
    11.24079722929388,
    // bar 26
    10.937883141487175,
    // bar 27
    10.620891488523807,
    // bar 28
    10.290827810772106,
    // bar 29
    9.948625824288383,
};

// Expected RSI(14) values for the same close series. Pine RSI semantics:
//
//   change = src - src[1]; up = max(change,0); down = max(-change,0).
//   rma_up = pine_rma(up, length); rma_dn = pine_rma(dn, length).
//   rsi = 100 - 100 / (1 + rma_up/rma_dn).
//
// Bar 0: change is NA, so up/dn are NA. RMA accumulates from bar 1 onwards.
// Bars 1..13: 13 valid up/dn samples accumulated, RMA still NA.
// Bar 14: 14 valid samples, RMA seed bar => first non-NA RSI value here.
static const std::vector<double> kRSI14_expected = {
    // bar 14: first non-NA
    63.63636363636363,
    // bar 15
    60.66666666666667,
    // bar 16
    57.76367187500001,
    // bar 17
    54.932847549649956,
    // bar 18
    52.17900802806168,
    // bar 19
    49.506299119609,
    // bar 20
    46.91819455964583,
    // bar 21
    44.41750271736374,
    // bar 22
    42.006382568940836,
    // bar 23
    39.6863677929065,
    // bar 24
    37.45839774643274,
    // bar 25
    35.3228540363955,
    // bar 26
    33.27960140225346,
    // bar 27
    31.328031672201917,
    // bar 28
    29.467109631875502,
    // bar 29
    27.69541974797187,
};

// --------------------------------------------------------------------
// Tests
// --------------------------------------------------------------------

static void test_rma14_warmup_and_smoothing() {
    ta::RMA rma(14);
    for (int i = 0; i < 13; ++i) {
        double v = rma.compute(kCloses[i]);
        CHECK_NA(v, "RMA(14) warmup bar should be NA");
    }
    // Bar 13 is the seed.
    int exp_idx = 0;
    for (int i = 13; i < (int)kCloses.size(); ++i, ++exp_idx) {
        double got = rma.compute(kCloses[i]);
        char tag[64];
        std::snprintf(tag, sizeof(tag), "RMA(14) bar=%d", i);
        CHECK_EXACT(got, kRMA14_expected[exp_idx], tag);
    }
}

static void test_rsi14_warmup_and_smoothing() {
    ta::RSI rsi(14);
    // Bars 0..13 are warmup (bar 0 has no change; bars 1..13 accumulate
    // into RMA but don't reach the seed count).
    for (int i = 0; i < 14; ++i) {
        double v = rsi.compute(kCloses[i]);
        CHECK_NA(v, "RSI(14) warmup bar should be NA");
    }
    // Bar 14 is the first non-NA.
    int exp_idx = 0;
    for (int i = 14; i < (int)kCloses.size(); ++i, ++exp_idx) {
        double got = rsi.compute(kCloses[i]);
        char tag[64];
        std::snprintf(tag, sizeof(tag), "RSI(14) bar=%d", i);
        CHECK_EXACT(got, kRSI14_expected[exp_idx], tag);
    }
}

// All-up sequence: every bar has positive change, no negative changes.
// rma_dn stays at 0 from the seed onwards => RSI = 100 (short-circuit).
static void test_rsi14_all_up_collapses_to_100() {
    ta::RSI rsi(14);
    for (int i = 0; i < 20; ++i) {
        double close = 10.0 + (double)i;
        double v = rsi.compute(close);
        if (i < 14) {
            char tag[64];
            std::snprintf(tag, sizeof(tag), "RSI(14) all-up warmup bar=%d", i);
            CHECK_NA(v, tag);
        } else {
            char tag[64];
            std::snprintf(tag, sizeof(tag), "RSI(14) all-up bar=%d should be 100", i);
            CHECK_EXACT(v, 100.0, tag);
        }
    }
}

// All-down sequence: every bar has negative change. rma_up stays at 0
// from the seed onwards => rs = 0 / rma_dn = 0 => RSI = 100 - 100/(1+0)
// = 0. Exercises the non-zero-divisor path of the RSI formula.
static void test_rsi14_all_down_collapses_to_0() {
    ta::RSI rsi(14);
    for (int i = 0; i < 20; ++i) {
        double close = 30.0 - (double)i;
        double v = rsi.compute(close);
        if (i < 14) {
            char tag[64];
            std::snprintf(tag, sizeof(tag), "RSI(14) all-down warmup bar=%d", i);
            CHECK_NA(v, tag);
        } else {
            char tag[64];
            std::snprintf(tag, sizeof(tag), "RSI(14) all-down bar=%d should be 0", i);
            CHECK_EXACT(v, 0.0, tag);
        }
    }
}

int main() {
    test_rma14_warmup_and_smoothing();
    test_rsi14_warmup_and_smoothing();
    test_rsi14_all_up_collapses_to_100();
    test_rsi14_all_down_collapses_to_0();

    std::printf("test_ta_rma_warmup: passed=%d failed=%d\n",
                tests_passed, tests_failed);
    return tests_failed == 0 ? 0 : 1;
}
