/*
 * test_margin_call_rules_tapes.cpp -- margin-call, admission and sizing rules
 * on TradingView's own tapes.
 *
 * tests/fixtures/margin_call_rules holds 265 `lab tv` tapes of synthetic
 * probes (README.md there names the families): one market entry -- or a
 * same-bar batch of entries "A", "B", "C" for the two counter controls --
 * placed at a fixed bar and closed with strategy.close_all() at another,
 * optionally behind a ledger of earlier closed trades or reversing an
 * explicit prior long, under a chosen capital, quantity (explicit, 100 % of
 * equity, or the script's floored equity / close), slippage, commission,
 * margin, process_orders_on_close and calc_on_order_fills. cases.tsv
 * (generated by build_cases.py from each tape's parameters.json) lists them
 * one per row. A chart range that ends before the scheduled close_all leaves
 * the position open at the range end.
 *
 * Every one of the 266 tapes is asserted (asserted=1), the 67
 * short-cutoff-gate tapes (a short's margin-call cut-off and slippage gate,
 * MarginScheduleSwitches) included. A tape the fixture marks asserted=0 would
 * be replayed and printed as GAP-MATCH or GAP-DIFF, then replayed with the
 * pooc_fee_sizing switch off and on, its rows checked by nothing; none is.
 *
 * The ten order-controls/ tapes (timed stop entries, strategy.cancel, an
 * SMA-readiness gate, a dynamic strategy.exit stop, a re-entry cooldown) are
 * not in cases.tsv: handwritten hosts make their scripts' strategy.* calls,
 * and each must match like an asserted tape.
 *
 * Each row is replayed through the Pine adapter on every bar of its chart's
 * exported window (bars/, from 00:00 UTC through to 00:00 UTC inclusive) and
 * every trade row TradingView reports -- its closed trades and a position
 * still open at the range end, which TradingView lists as a trade closed at
 * the last bar's close with an empty Signal -- must be the engine's report
 * row at the same index: side, quantity in lots, entry and exit price in
 * ticks, entry and exit time. The range-end rows come from the host itself:
 * PineStrategyHost records a position still open after the last bar as
 * report rows (scheduler_record_range_end, read back through
 * report_trade_count() / get_report_trade()), so nothing is emulated here.
 *
 * kKnownDivergences names the asserted tapes the engine is known not to
 * reproduce yet. Every unlisted asserted tape must match and every listed tape
 * must still differ, so the list shrinks as the engine learns a rule.
 *
 * Each margin rule the adapter implements sits behind its own switch
 * (pineforge::source::detail::MarginRuleSwitches, MarginScheduleSwitches and
 * MarginOpeningSwitches).
 * The tree ships every rule on, which this test checks; it replays the tapes
 * with the shipped switches against kKnownDivergences, turns each rule off
 * alone from there and requires a load-bearing one to cost at least one tape,
 * and turns all of them off to recover the tapes the engine matched before
 * the rules.
 */

#include <pineforge/bar.hpp>
#include <pineforge/source/pine_adapter.hpp>
#include <pineforge/source/pine_strategy_host.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

using namespace pineforge;

static int tests_passed = 0;
static int tests_failed = 0;

#define CHECK(expr)                                                            \
    do {                                                                       \
        if (!(expr)) {                                                         \
            std::printf("  FAIL  %s:%d  %s\n", __FILE__, __LINE__, #expr);     \
            ++tests_failed;                                                    \
        } else {                                                               \
            ++tests_passed;                                                    \
        }                                                                      \
    } while (0)

#ifndef PINEFORGE_MARGIN_CALL_RULES_FIXTURE_DIR
#error "PINEFORGE_MARGIN_CALL_RULES_FIXTURE_DIR must name tests/fixtures/margin_call_rules"
#endif

namespace {

constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();
constexpr std::int64_t kMinute = 60'000;
// cases.tsv's qty column: "percent" (default_qty_type percent of equity, 100)
// and "source_raw" (the script's floor(equity / close / step) * step).
constexpr double kPercentQty = -1.0;
constexpr double kSourceRawQty = -2.0;
// Asserted tapes and their TradingView rows; the recorded-only short-cutoff-gate
// tapes and their rows.
constexpr std::size_t kTapes = 266;
constexpr std::size_t kTvRows = 602;
constexpr std::size_t kRecordedTapes = 0;
constexpr std::size_t kRecordedTvRows = 0;
// The asserted tapes the engine matches with every margin rule off (before
// the rules).
constexpr std::size_t kTapesBeforeRules = 140;

using pineforge::source::detail::MarginRuleSwitches;
using pineforge::source::detail::MarginScheduleSwitches;

struct Ablation {
    const char* name;
    bool MarginRuleSwitches::*flag;
    bool load_bearing = true;
};

// Every margin rule on. Every field of MarginRuleSwitches is named here and in
// the ablation table: the static_assert stops the build when one is added.
MarginRuleSwitches all_rules_on() {
    static_assert(sizeof(MarginRuleSwitches) == 17 * sizeof(bool),
                  "MarginRuleSwitches changed: name its new field here and in the ablation table");
    MarginRuleSwitches on;
    on.decimal_sizing = true;
    on.slipped_signal_admission = true;
    on.unified_placement = true;
    on.fill_price_recheck = true;
    on.close_first_admission = true;
    on.gain_loss_money = true;
    on.dust_unit_call = true;
    on.long_open_close_checks = true;
    on.negative_free_cash_call = true;
    on.coof_next_point_close = true;
    on.close_point_reversal = true;
    on.pooc_fee_sizing = true;
    on.point_fills_before_margin = true;
    on.point_order_trailing_exits = true;
    on.pyramiding_ledger_records = true;
    on.exit_child_tombstones = true;
    on.tie_reversal_beside_exits = true;
    return on;
}

bool same_switches(const MarginRuleSwitches& a, const MarginRuleSwitches& b) {
    return std::memcmp(&a, &b, sizeof(MarginRuleSwitches)) == 0;
}

// Every schedule rule on; every field is named here and in the ablation table.
MarginScheduleSwitches all_schedule_rules_on() {
    static_assert(sizeof(MarginScheduleSwitches) == 10 * sizeof(bool),
                  "MarginScheduleSwitches changed: name its new field here and in the ablation table");
    MarginScheduleSwitches on;
    on.short_call_gate = true;
    on.short_path_points = true;
    on.lagged_short_follow_up = true;
    on.pending_veto_first = true;
    on.frozen_reversal_close = true;
    on.add_signal_close = true;
    on.whole_share_lagged_follow_up = true;
    on.long_call_gain_loss = true;
    on.close_call_follow_up_at_open = true;
    on.close_follow_up_after_script = true;
    return on;
}

struct ScheduleAblation {
    const char* name;
    bool MarginScheduleSwitches::*flag;
    bool load_bearing = true;
};

// Tapes the engine does not reproduce yet: fixture path and a one-line reason.
// A listed tape that starts matching fails the test until its entry is
// removed.
const std::vector<std::pair<std::string, std::string>> kKnownDivergences = {
    {"coof/coof-low-call-s1",
     "a slipped long's one-unit call at the low (not implemented: test_pooc_open_money_event_l4b pins no call there)"},
    {"schedule/fresh-p2-coof",
     "a carried short's source-close / fresh-opening call schedule (not implemented)"},
    {"schedule/fresh-plus02-coof",
     "a carried short's source-close / fresh-opening call schedule (not implemented)"},
    {"quantum/short-m50-s0",
     "a short's call quantum at margin 50 (not implemented)"},
    {"quantum/short-m50-s2",
     "a short's call quantum at margin 50 (not implemented)"},
    {"quantum/short-m50-s5",
     "a short's call quantum at margin 50 (not implemented)"},
    {"counter-controls/margin_fractional_boundary",
     "a multi-lot short's call at the high, split first in first out (not implemented)"},
    {"counter-controls/margin_batch_50",
     "a multi-lot long at margin 50 with a per-contract fee (not implemented)"},
};

std::string fixture(const std::string& relative) {
    return std::string(PINEFORGE_MARGIN_CALL_RULES_FIXTURE_DIR) + "/" + relative;
}

std::vector<std::string> split(const std::string& text, char separator) {
    std::vector<std::string> cells;
    std::string cell;
    std::istringstream fields(text);
    while (std::getline(fields, cell, separator)) cells.push_back(cell);
    if (!text.empty() && text.back() == separator) cells.emplace_back();
    return cells;
}

std::int64_t days_from_civil(int y, unsigned m, unsigned d) {
    y -= m <= 2;
    const int era = (y >= 0 ? y : y - 399) / 400;
    const unsigned yoe = static_cast<unsigned>(y - era * 400);
    const unsigned doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return static_cast<std::int64_t>(era) * 146097 + static_cast<std::int64_t>(doe) - 719468;
}

// A tape stamp "YYYY-MM-DD HH:MM" rendered at UTC+8 -> UTC milliseconds.
std::int64_t tape_ms(const std::string& stamp) {
    int y = 0, mo = 0, d = 0, h = 0, mi = 0;
    if (std::sscanf(stamp.c_str(), "%d-%d-%d %d:%d", &y, &mo, &d, &h, &mi) != 5) return -1;
    const std::int64_t days = days_from_civil(y, static_cast<unsigned>(mo),
                                              static_cast<unsigned>(d));
    return ((days * 24 + h - 8) * 60 + mi) * kMinute;
}

struct LedgerTrade {
    std::int64_t entry_time;
    std::int64_t close_time;
    bool is_long;
    double quantity;
};

struct Case {
    std::string path;
    std::string bars;
    double tick = 0.0;
    double step = 0.0;
    double capital = 0.0;
    bool is_long = true;
    double qty = 0.0;
    int slippage = 0;
    double fee = 0.0;
    bool cash_per_contract = false;
    double margin = 100.0;
    bool pooc = false;
    bool coof = false;
    std::int64_t entry_ms = 0;
    std::int64_t close_ms = 0;
    std::int64_t to_ms = 0;
    double stop = kNaN;
    std::vector<LedgerTrade> prior;
    std::vector<double> lots;
    int pyramiding = 1;
    // An explicit prior long "before" the main order reverses (0 = none).
    std::int64_t reversal_ms = 0;
    double reversal_qty = 0.0;
    bool asserted = true;
};

std::vector<Case> load_cases() {
    std::ifstream in(fixture("cases.tsv"));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    std::map<std::string, std::size_t> column;
    const std::vector<std::string> header = split(line, '\t');
    for (std::size_t i = 0; i < header.size(); ++i) column[header[i]] = i;
    for (const char* name : {"path", "bars", "tick", "step", "capital", "direction", "qty",
                             "slippage", "fee", "fee_type", "margin", "pooc", "coof", "entry_ms",
                             "close_ms", "to_ms", "stop", "prior", "lots", "pyramiding",
                             "reversal", "asserted"}) {
        CHECK(column.count(name) == 1);
        if (!column.count(name)) return {};
    }
    std::vector<Case> cases;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        const std::vector<std::string> cell = split(line, '\t');
        CHECK(cell.size() == header.size());
        if (cell.size() != header.size()) continue;
        auto at = [&](const char* name) -> const std::string& { return cell[column[name]]; };
        auto number = [&](const char* name) { return std::strtod(at(name).c_str(), nullptr); };
        auto ms = [&](const std::string& text) {
            return static_cast<std::int64_t>(std::strtoll(text.c_str(), nullptr, 10));
        };
        Case c;
        c.path = at("path");
        c.bars = at("bars");
        c.tick = number("tick");
        c.step = number("step");
        c.capital = number("capital");
        c.is_long = at("direction") == "long";
        CHECK(at("direction") == "long" || at("direction") == "short");
        c.qty = at("qty") == "percent" ? kPercentQty
              : at("qty") == "source_raw" ? kSourceRawQty : number("qty");
        c.slippage = std::atoi(at("slippage").c_str());
        c.fee = number("fee");
        c.cash_per_contract = at("fee_type") == "cash_per_contract";
        CHECK(at("fee_type") == "percent" || at("fee_type") == "cash_per_contract");
        c.margin = number("margin");
        c.pooc = at("pooc") == "1";
        c.coof = at("coof") == "1";
        c.entry_ms = ms(at("entry_ms"));
        c.close_ms = ms(at("close_ms"));
        c.to_ms = ms(at("to_ms"));
        if (!at("stop").empty()) c.stop = number("stop");
        if (!at("prior").empty()) {
            for (const std::string& trade : split(at("prior"), ';')) {
                const std::vector<std::string> part = split(trade, ':');
                CHECK(part.size() == 4);
                if (part.size() != 4) continue;
                c.prior.push_back({ms(part[0]), ms(part[1]), part[2] == "long",
                                   std::strtod(part[3].c_str(), nullptr)});
            }
        }
        if (!at("lots").empty()) {
            for (const std::string& lot : split(at("lots"), ';'))
                c.lots.push_back(std::strtod(lot.c_str(), nullptr));
        }
        c.pyramiding = std::atoi(at("pyramiding").c_str());
        if (!at("reversal").empty()) {
            const std::vector<std::string> part = split(at("reversal"), ':');
            CHECK(part.size() == 2);
            if (part.size() == 2) {
                c.reversal_ms = ms(part[0]);
                c.reversal_qty = std::strtod(part[1].c_str(), nullptr);
            }
        }
        CHECK(at("asserted") == "1" || at("asserted") == "0");
        c.asserted = at("asserted") == "1";
        cases.push_back(std::move(c));
    }
    return cases;
}

// Every row of a bars/ file: the chart's window, from 00:00 UTC through to
// 00:00 UTC inclusive.
std::vector<Bar> load_bars(const std::string& name) {
    std::ifstream in(fixture("bars/" + name));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    CHECK(line == "timestamp,open,high,low,close,volume");
    std::vector<Bar> bars;
    while (std::getline(in, line)) {
        const std::vector<std::string> cell = split(line, ',');
        CHECK(cell.size() == 6);
        if (cell.size() != 6) continue;
        bars.push_back({std::strtod(cell[1].c_str(), nullptr), std::strtod(cell[2].c_str(), nullptr),
                        std::strtod(cell[3].c_str(), nullptr), std::strtod(cell[4].c_str(), nullptr),
                        std::strtod(cell[5].c_str(), nullptr),
                        static_cast<std::int64_t>(std::strtoll(cell[0].c_str(), nullptr, 10))});
    }
    return bars;
}

// One trade row as both sides report it: prices in ticks, quantity in lots.
struct Row {
    bool is_long = true;
    long long qty_lots = 0;
    long long entry_ticks = 0;
    long long exit_ticks = 0;
    std::int64_t entry_ms = 0;
    std::int64_t exit_ms = 0;
};

Row make_row(bool is_long, double qty, double entry_price, double exit_price,
             std::int64_t entry_ms, std::int64_t exit_ms, const Case& c) {
    return {is_long, std::llround(qty / c.step), std::llround(entry_price / c.tick),
            std::llround(exit_price / c.tick), entry_ms, exit_ms};
}

// TradingView's rows: each Exit row paired with the Entry row of its trade
// number, in trade-number order. tv_trades.csv starts with a UTF-8 BOM; its
// header is "Trade number,Type,Date and time,Signal,Price <CCY>,Size (qty),...".
std::vector<Row> tape_rows(const Case& c) {
    std::ifstream in(fixture(c.path + "/tv_trades.csv"));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    if (line.rfind("\xEF\xBB\xBF", 0) == 0) line.erase(0, 3);
    CHECK(line.rfind("Trade number,Type,Date and time,Signal,Price ", 0) == 0);
    struct Side { bool seen = false; bool is_long = true; double price = 0.0; double qty = 0.0; std::int64_t ms = 0; };
    std::map<int, std::pair<Side, Side>> by_number;  // (entry, exit)
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        const std::vector<std::string> cell = split(line, ',');
        CHECK(cell.size() >= 6);
        if (cell.size() < 6) continue;
        const int number = std::atoi(cell[0].c_str());
        const bool entry = cell[1].rfind("Entry", 0) == 0;
        CHECK(entry || cell[1].rfind("Exit", 0) == 0);
        Side& side = entry ? by_number[number].first : by_number[number].second;
        CHECK(!side.seen);
        side.seen = true;
        side.is_long = cell[1].size() >= 4 && cell[1].compare(cell[1].size() - 4, 4, "long") == 0;
        side.ms = tape_ms(cell[2]);
        side.price = std::strtod(cell[4].c_str(), nullptr);
        side.qty = std::strtod(cell[5].c_str(), nullptr);
    }
    std::vector<Row> rows;
    for (const auto& [number, pair] : by_number) {
        const Side& entry = pair.first;
        const Side& exit = pair.second;
        CHECK(entry.seen && exit.seen);
        if (!entry.seen || !exit.seen) continue;
        CHECK(entry.is_long == exit.is_long);
        rows.push_back(make_row(exit.is_long, exit.qty, entry.price, exit.price, entry.ms,
                                exit.ms, c));
    }
    return rows;
}

// engine_harness.cpp's probe host (counter_harness.cpp's when `lots` is set),
// configured from one cases.tsv row.
class RuleHost final : public source::PineStrategyHost {
public:
    explicit RuleHost(const Case& c) : c_(c) {
        attach_pine_execution_adapter();
        source::PineStrategyConfig configuration;
        configuration.initial_capital = c.capital;
        configuration.pyramiding = c.pyramiding;
        configuration.margin_long = c.margin;
        configuration.margin_short = c.margin;
        configuration.commission_type = static_cast<int>(
            c.cash_per_contract ? CommissionType::CASH_PER_CONTRACT : CommissionType::PERCENT);
        configuration.commission_value = c.fee;
        configuration.slippage = c.slippage;
        configuration.process_orders_on_close = c.pooc;
        configuration.calc_on_order_fills = c.coof;
        if (c.qty == kPercentQty) {
            configuration.default_qty_type = static_cast<int>(QtyType::PERCENT_OF_EQUITY);
            configuration.default_qty_value = 100.0;
        }
        configure_pine_strategy(configuration);
        set_syminfo_mintick(c.tick);
        set_syminfo_metadata("qty_step", c.step);
    }

    void on_source_bar(const Bar& bar) override {
        if (!c_.lots.empty()) {
            // counter_harness.cpp: one same-bar batch "A", "B", "C", ... then close_all.
            if (bar.timestamp == c_.entry_ms) {
                for (std::size_t lot = 0; lot < c_.lots.size(); ++lot)
                    strategy_entry(std::string(1, static_cast<char>('A' + lot)), c_.is_long,
                                   kNaN, kNaN, c_.lots[lot]);
            }
            if (bar.timestamp == c_.close_ms) strategy_close_all();
            return;
        }
        for (std::size_t index = 0; index < c_.prior.size(); ++index) {
            const LedgerTrade& trade = c_.prior[index];
            if (bar.timestamp == trade.entry_time && signed_position_size() == 0.0)
                strategy_entry("ledger-" + std::to_string(index), trade.is_long, kNaN, kNaN,
                               trade.quantity);
            if (bar.timestamp == trade.close_time) strategy_close_all();
        }
        // A reversal tape: the explicit prior long "before", then the main
        // order "after" reverses it (its script has no flat guard).
        const bool reversal = c_.reversal_ms != 0;
        if (reversal && bar.timestamp == c_.reversal_ms && signed_position_size() == 0.0)
            strategy_entry("before", true, kNaN, kNaN, c_.reversal_qty);
        if (bar.timestamp == c_.entry_ms && (reversal || signed_position_size() == 0.0)) {
            const double quantity =
                c_.qty == kSourceRawQty ? std::floor(current_equity() / bar.close / c_.step) * c_.step
                : c_.qty < 0.0          ? kNaN
                                        : c_.qty;
            strategy_entry(reversal ? "after" : "probe", c_.is_long, kNaN, c_.stop, quantity);
        }
        if (bar.timestamp == c_.close_ms) strategy_close_all();
    }

private:
    Case c_;
};

struct Outcome {
    std::vector<Row> rows;
    std::string error;
};

Outcome replay(const Case& c, const std::vector<Bar>& bars) {
    RuleHost host(c);
    host.run(bars.data(), static_cast<int>(bars.size()), "15", "15");
    Outcome outcome;
    outcome.error = host.last_error();
    // Report rows: the closed trades, then the host's range-end rows for a
    // position still open after the last bar.
    for (int index = 0; index < host.report_trade_count(); ++index) {
        const Trade& trade = host.get_report_trade(index);
        outcome.rows.push_back(make_row(trade.is_long, trade.qty, trade.entry_price,
                                        trade.exit_price, trade.entry_time, trade.exit_time, c));
    }
    return outcome;
}

std::string first_difference(const std::vector<Row>& tv, const Outcome& engine) {
    if (!engine.error.empty()) return "engine error: " + engine.error;
    const std::size_t common = std::min(tv.size(), engine.rows.size());
    std::string count;
    if (tv.size() != engine.rows.size())
        count = "rows tv=" + std::to_string(tv.size()) + " engine=" + std::to_string(engine.rows.size());
    for (std::size_t i = 0; i < common; ++i) {
        const Row& t = tv[i];
        const Row& e = engine.rows[i];
        auto field = [&](const char* name, long long expected, long long actual) {
            std::string text = "row " + std::to_string(i + 1) + " " + name + " tv=" +
                               std::to_string(expected) + " engine=" + std::to_string(actual);
            return count.empty() ? text : text + " (" + count + ")";
        };
        if (t.is_long != e.is_long) return field("long", t.is_long, e.is_long);
        if (t.qty_lots != e.qty_lots) return field("qty_lots", t.qty_lots, e.qty_lots);
        if (t.entry_ticks != e.entry_ticks) return field("entry_ticks", t.entry_ticks, e.entry_ticks);
        if (t.exit_ticks != e.exit_ticks) return field("exit_ticks", t.exit_ticks, e.exit_ticks);
        if (t.entry_ms != e.entry_ms) return field("entry_ms", t.entry_ms, e.entry_ms);
        if (t.exit_ms != e.exit_ms) return field("exit_ms", t.exit_ms, e.exit_ms);
    }
    return count;
}

// ---------------------------------------------------------------- order controls
// order-controls/ holds ten order-control tapes: timed stop entries,
// strategy.cancel, an SMA-readiness gate, a dynamic strategy.exit stop and a
// re-entry cooldown observed through strategy.position_size[1] and bar_index.
// Each script is replayed by a handwritten host below that makes the same
// strategy.* calls in the same order as its strategy.pine; ta.sma and ta.atr
// are computed here over the fed bars as Pine defines them. Every bars/ window
// is the chart's from..to range, so a script sees exactly the history
// TradingView loaded for it (the warmup-*-preload tapes start earlier for
// that reason).

std::int64_t utc_ms(int y, unsigned mo, unsigned d, int h, int mi) {
    return ((days_from_civil(y, mo, d) * 24 + h) * 60 + mi) * kMinute;
}

class ControlHost : public source::PineStrategyHost {
public:
    ControlHost(double capital, bool pooc, bool percent_default, double tick, double step) {
        attach_pine_execution_adapter();
        source::PineStrategyConfig configuration;
        configuration.initial_capital = capital;
        configuration.pyramiding = 1;
        configuration.margin_long = 100.0;
        configuration.margin_short = 100.0;
        configuration.process_orders_on_close = pooc;
        if (percent_default) {
            configuration.default_qty_type = static_cast<int>(QtyType::PERCENT_OF_EQUITY);
            configuration.default_qty_value = 100.0;
        }
        configure_pine_strategy(configuration);
        set_syminfo_mintick(tick);
        set_syminfo_metadata("qty_step", step);
    }
};

// ta.sma(close, n) over the fed bars: na until n closes, then
// sum(close[i] / n, i = 0 .. n - 1).
class SmaSeries {
public:
    explicit SmaSeries(std::size_t length) : length_(length) {}
    void push(const std::vector<double>& closes) {
        previous_ = current_;
        current_ = kNaN;
        if (closes.size() < length_) return;
        double sum = 0.0;
        for (std::size_t i = 0; i < length_; ++i)
            sum += closes[closes.size() - 1 - i] / static_cast<double>(length_);
        current_ = sum;
    }
    // x > x[1], false when either is na.
    bool rising() const {
        return !std::isnan(current_) && !std::isnan(previous_) && current_ > previous_;
    }

private:
    std::size_t length_;
    double current_ = kNaN;
    double previous_ = kNaN;
};

// order-11 / order-38: an unconditional timed stop entry, then close_all.
class UnconditionalStopHost final : public ControlHost {
public:
    UnconditionalStopHost(double capital, double tick, double step, std::int64_t entry_ms,
                          double qty, double stop, std::int64_t close_ms)
        : ControlHost(capital, false, false, tick, step), entry_ms_(entry_ms), qty_(qty),
          stop_(stop), close_ms_(close_ms) {}
    void on_source_bar(const Bar& bar) override {
        if (bar.timestamp == entry_ms_) strategy_entry("probe", true, kNaN, stop_, qty_);
        if (bar.timestamp == close_ms_) strategy_close_all();
    }

private:
    std::int64_t entry_ms_;
    double qty_;
    double stop_;
    std::int64_t close_ms_;
};

// warmup-btc-*: an SMA-readiness gate, a timed stop, a next-bar cancel.
class WarmupBtcHost final : public ControlHost {
public:
    WarmupBtcHost(double tick, double step) : ControlHost(99600.36216, false, false, tick, step) {}
    void on_source_bar(const Bar& bar) override {
        closes_.push_back(bar.close);
        fast_.push(closes_);
        middle_.push(closes_);
        slow_.push(closes_);
        const int up = int(fast_.rising()) + int(middle_.rising()) + int(slow_.rising());
        if (bar.timestamp == utc_ms(2025, 4, 2, 8, 0) && up >= 2)
            strategy_entry("probe", true, kNaN, 84462.16, 1.17923);
        if (bar.timestamp == utc_ms(2025, 4, 2, 8, 15)) strategy_cancel("probe");
        if (bar.timestamp == utc_ms(2025, 4, 2, 9, 0)) strategy_close_all();
    }

private:
    std::vector<double> closes_;
    SmaSeries fast_{21}, middle_{84}, slow_{252};
};

// warmup-eur-*: the SMA gate with a consumed first attempt and a re-placed stop.
class WarmupEurHost final : public ControlHost {
public:
    WarmupEurHost(double tick, double step) : ControlHost(100000.0, false, false, tick, step) {}
    void on_source_bar(const Bar& bar) override {
        closes_.push_back(bar.close);
        fast_.push(closes_);
        middle_.push(closes_);
        slow_.push(closes_);
        const int up = int(fast_.rising()) + int(middle_.rising()) + int(slow_.rising());
        if (bar.timestamp == utc_ms(2025, 4, 2, 3, 0) && up >= 2) {
            consumed_ = true;
            strategy_entry("probe", true, kNaN, 1.08018, 92577.16);
        }
        if (bar.timestamp == utc_ms(2025, 4, 2, 3, 15)) strategy_cancel("probe");
        if (bar.timestamp == utc_ms(2025, 4, 2, 8, 45) && !consumed_ && up >= 2)
            strategy_entry("probe", true, kNaN, 1.08018, 92577.16);
        if (bar.timestamp == utc_ms(2025, 4, 2, 9, 15) && consumed_)
            strategy_entry("probe", true, kNaN, 1.08031, 92566.02);
        if (bar.timestamp == utc_ms(2025, 4, 2, 9, 45)) strategy_close_all();
    }

private:
    std::vector<double> closes_;
    SmaSeries fast_{21}, middle_{84}, slow_{252};
    bool consumed_ = false;
};

// cooldown-*: a seed short behind a fixed exit stop, then a percent-of-equity
// candidate short gated by a cooldown that observes the seed's exit through
// strategy.position_size[1] -- before the candidate check (early observer) or
// after it (late observer).
class CooldownStopHost final : public ControlHost {
public:
    CooldownStopHost(double tick, double step, const char* exit_id, std::int64_t exit_ms,
                     double exit_stop, bool early_observer)
        : ControlHost(69001.53831500027, true, true, tick, step), exit_id_(exit_id),
          exit_ms_(exit_ms), exit_stop_(exit_stop), early_observer_(early_observer) {}
    void on_source_bar(const Bar& bar) override {
        const double position = signed_position_size();
        const int index = pine_bar_index();
        if (bar.timestamp == utc_ms(2026, 1, 8, 19, 45))
            strategy_entry("seed", false, kNaN, kNaN, 22.186);
        if (bar.timestamp == exit_ms_) strategy_exit(exit_id_, "seed", kNaN, exit_stop_);
        if (early_observer_) observe(position, index);
        if (bar.timestamp == utc_ms(2026, 1, 8, 23, 30) && position >= 0.0 &&
            (!observed_ || index - observed_exit_ > 4))
            strategy_entry("candidate", false);
        if (!early_observer_) observe(position, index);
        if (bar.timestamp == utc_ms(2026, 1, 9, 1, 0)) strategy_close_all();
        previous_position_ = position;
    }

private:
    void observe(double position, int index) {
        if (previous_position_ < 0.0 && position == 0.0) {
            observed_ = true;
            observed_exit_ = index;
        }
    }
    const char* exit_id_;
    std::int64_t exit_ms_;
    double exit_stop_;
    bool early_observer_;
    double previous_position_ = kNaN;
    bool observed_ = false;
    int observed_exit_ = 0;
};

// cooldown-atr-entry-clear: the seed short behind a dynamic ATR stop
// re-placed every bar from position_avg_price and the running trough.
class CooldownAtrHost final : public ControlHost {
public:
    CooldownAtrHost(double tick, double step)
        : ControlHost(69001.53831500027, true, true, tick, step) {}
    void on_source_bar(const Bar& bar) override {
        const double position = signed_position_size();
        const int index = pine_bar_index();
        const std::int64_t seed_ms = utc_ms(2026, 1, 8, 19, 45);
        if (bar.timestamp == seed_ms) strategy_entry("seed", false, kNaN, kNaN, 22.186);
        const double volatility = atr(bar);
        if (bar.timestamp == seed_ms) {
            captured_ = volatility;
            trough_ = bar.low;
        }
        if (position < 0.0) {
            trough_ = std::isnan(trough_) ? bar.low : std::min(trough_, bar.low);
            const double working = std::isnan(captured_) ? volatility : captured_;
            const double reference = position_avg_price();
            const double stop = trough_ <= reference - 2.0 * working
                                    ? std::min(reference - 0.1 * working, trough_ + 3.2 * working)
                                    : reference + 2.2 * working;
            strategy_exit("dynamic", "seed", kNaN, stop);
        }
        if (bar.timestamp == utc_ms(2026, 1, 8, 23, 30) && position >= 0.0 &&
            (!observed_ || index - observed_exit_ > 4))
            strategy_entry("candidate", false);
        if (previous_position_ < 0.0 && position == 0.0) {
            observed_ = true;
            observed_exit_ = index;
        }
        if (position == 0.0) {
            captured_ = kNaN;
            trough_ = kNaN;
        }
        if (bar.timestamp == utc_ms(2026, 1, 9, 1, 0)) strategy_close_all();
        previous_position_ = position;
    }

private:
    // ta.atr(14) = ta.rma(true range, 14): the first value the SMA of the
    // first 14 true ranges, then alpha * tr + (1 - alpha) * previous.
    double atr(const Bar& bar) {
        const double range = std::isnan(previous_close_)
                                 ? bar.high - bar.low
                                 : std::max(std::max(bar.high - bar.low,
                                                     std::fabs(bar.high - previous_close_)),
                                            std::fabs(bar.low - previous_close_));
        previous_close_ = bar.close;
        ranges_.push_back(range);
        constexpr std::size_t kLength = 14;
        if (std::isnan(rma_)) {
            if (ranges_.size() >= kLength) {
                double sum = 0.0;
                for (std::size_t i = 0; i < kLength; ++i)
                    sum += ranges_[ranges_.size() - 1 - i] / static_cast<double>(kLength);
                rma_ = sum;
            }
        } else {
            const double alpha = 1.0 / static_cast<double>(kLength);
            rma_ = alpha * range + (1.0 - alpha) * rma_;
        }
        return rma_;
    }
    std::vector<double> ranges_;
    double previous_close_ = kNaN;
    double rma_ = kNaN;
    double captured_ = kNaN;
    double trough_ = kNaN;
    double previous_position_ = kNaN;
    bool observed_ = false;
    int observed_exit_ = 0;
};

struct OrderControl {
    const char* path;
    const char* bars;
    double tick;
    double step;
};

const OrderControl kOrderControls[] = {
    {"order-controls/cooldown-atr-entry-clear", "eth-own-2026-01-08-2026-01-10.csv", 0.01, 0.0001},
    {"order-controls/cooldown-closepoint-early-observer", "eth-own-2026-01-08-2026-01-10.csv", 0.01, 0.0001},
    {"order-controls/cooldown-closepoint-late-observer", "eth-own-2026-01-08-2026-01-10.csv", 0.01, 0.0001},
    {"order-controls/cooldown-resting-late-observer", "eth-own-2026-01-08-2026-01-10.csv", 0.01, 0.0001},
    {"order-controls/order-11-unconditional", "btc-own-2025-04-01-2025-04-03.csv", 0.01, 1e-05},
    {"order-controls/order-38-unconditional", "eur-own-2025-04-01-2025-04-03.csv", 1e-05, 0.01},
    {"order-controls/warmup-btc-preload", "btc-own-2025-03-29-2025-04-03.csv", 0.01, 1e-05},
    {"order-controls/warmup-btc-range", "btc-own-2025-04-01-2025-04-03.csv", 0.01, 1e-05},
    {"order-controls/warmup-eur-preload-deep", "eur-own-2025-03-27-2025-04-03.csv", 1e-05, 0.01},
    {"order-controls/warmup-eur-range", "eur-own-2025-04-01-2025-04-03.csv", 1e-05, 0.01},
};
constexpr std::size_t kOrderControlTvRows = 21;

std::unique_ptr<source::PineStrategyHost> order_control_host(const std::string& path, double tick,
                                                             double step) {
    const std::string name = path.substr(path.find('/') + 1);
    if (name == "cooldown-atr-entry-clear") return std::make_unique<CooldownAtrHost>(tick, step);
    if (name == "cooldown-closepoint-early-observer")
        return std::make_unique<CooldownStopHost>(tick, step, "closepoint", utc_ms(2026, 1, 8, 23, 15),
                                                  3109.0, true);
    if (name == "cooldown-closepoint-late-observer")
        return std::make_unique<CooldownStopHost>(tick, step, "closepoint", utc_ms(2026, 1, 8, 23, 15),
                                                  3109.0, false);
    if (name == "cooldown-resting-late-observer")
        return std::make_unique<CooldownStopHost>(tick, step, "resting", utc_ms(2026, 1, 8, 23, 0),
                                                  3120.49, false);
    if (name == "order-11-unconditional")
        return std::make_unique<UnconditionalStopHost>(99600.36216, tick, step, utc_ms(2025, 4, 2, 8, 0),
                                                       1.17923, 84462.16, utc_ms(2025, 4, 2, 9, 45));
    if (name == "order-38-unconditional")
        return std::make_unique<UnconditionalStopHost>(100000.0, tick, step, utc_ms(2025, 4, 2, 8, 45),
                                                       92577.16, 1.08018, utc_ms(2025, 4, 2, 9, 45));
    if (name == "warmup-btc-preload" || name == "warmup-btc-range")
        return std::make_unique<WarmupBtcHost>(tick, step);
    if (name == "warmup-eur-preload-deep" || name == "warmup-eur-range")
        return std::make_unique<WarmupEurHost>(tick, step);
    return nullptr;
}

Outcome replay_control(source::PineStrategyHost& host, const Case& c, const std::vector<Bar>& bars) {
    host.run(bars.data(), static_cast<int>(bars.size()), "15", "15");
    Outcome outcome;
    outcome.error = host.last_error();
    for (int index = 0; index < host.report_trade_count(); ++index) {
        const Trade& trade = host.get_report_trade(index);
        outcome.rows.push_back(make_row(trade.is_long, trade.qty, trade.entry_price,
                                        trade.exit_price, trade.entry_time, trade.exit_time, c));
    }
    return outcome;
}

bool same_rows(const Outcome& left, const Outcome& right) {
    if (left.error != right.error || left.rows.size() != right.rows.size()) return false;
    for (std::size_t i = 0; i < left.rows.size(); ++i) {
        const Row& a = left.rows[i];
        const Row& b = right.rows[i];
        if (a.is_long != b.is_long || a.qty_lots != b.qty_lots || a.entry_ticks != b.entry_ticks ||
            a.exit_ticks != b.exit_ticks || a.entry_ms != b.entry_ms || a.exit_ms != b.exit_ms)
            return false;
    }
    return true;
}

// The asserted tapes that match under the current switches.
std::set<std::string> matching_tapes(const std::vector<Case>& cases,
                                     std::map<std::string, std::vector<Bar>>& feeds) {
    std::set<std::string> matched;
    for (const Case& c : cases) {
        if (!c.asserted) continue;
        auto feed = feeds.find(c.bars);
        if (feed == feeds.end()) feed = feeds.emplace(c.bars, load_bars(c.bars)).first;
        if (first_difference(tape_rows(c), replay(c, feed->second)).empty()) matched.insert(c.path);
    }
    return matched;
}

}  // namespace

int main() {
    std::printf("=== margin_call_rules: TradingView tapes of margin-call, admission and sizing rules ===\n");
    const std::vector<Case> cases = load_cases();
    const std::size_t asserted_tapes =
        static_cast<std::size_t>(std::count_if(cases.begin(), cases.end(),
                                               [](const Case& c) { return c.asserted; }));
    CHECK(asserted_tapes == kTapes);
    CHECK(cases.size() - asserted_tapes == kRecordedTapes);

    // The tree ships every rule on (MarginRuleSwitches).
    auto& switches = pineforge::source::detail::margin_rule_switches();
    const MarginRuleSwitches tree_defaults = switches;
    const MarginRuleSwitches all_on = all_rules_on();
    CHECK(same_switches(tree_defaults, all_on));
    auto& schedule = pineforge::source::detail::margin_schedule_switches();
    const MarginScheduleSwitches schedule_defaults = schedule;
    const MarginScheduleSwitches schedule_on = all_schedule_rules_on();
    CHECK(std::memcmp(&schedule_defaults, &schedule_on, sizeof(MarginScheduleSwitches)) == 0);

    std::map<std::string, std::string> known;
    for (const auto& [path, reason] : kKnownDivergences) {
        CHECK(!reason.empty());
        CHECK(known.emplace(path, reason).second);
    }
    std::set<std::string> listed_paths;
    std::map<std::string, std::vector<Bar>> feeds;
    std::size_t matched = 0;
    std::size_t tv_rows = 0;
    std::size_t recorded_matched = 0;
    std::size_t recorded_tv_rows = 0;
    std::vector<const Case*> recorded;
    for (const Case& c : cases) {
        auto feed = feeds.find(c.bars);
        if (feed == feeds.end()) feed = feeds.emplace(c.bars, load_bars(c.bars)).first;
        const std::vector<Bar>& bars = feed->second;
        CHECK(!bars.empty() && bars.back().timestamp <= c.to_ms);
        const std::vector<Row> tv = tape_rows(c);
        const Outcome engine = replay(c, bars);
        const std::string difference = first_difference(tv, engine);
        const bool match = difference.empty();
        if (!c.asserted) {
            // Recorded, not asserted: the short cut-off and slippage gate.
            recorded.push_back(&c);
            recorded_tv_rows += tv.size();
            if (match) {
                ++recorded_matched;
                std::printf("GAP-MATCH %s\n", c.path.c_str());
            } else {
                std::printf("GAP-DIFF %s %s\n", c.path.c_str(), difference.c_str());
            }
            continue;
        }
        listed_paths.insert(c.path);
        tv_rows += tv.size();
        if (match) {
            ++matched;
            std::printf("MATCH %s\n", c.path.c_str());
        } else {
            std::printf("DIFF %s %s\n", c.path.c_str(), difference.c_str());
        }
        const auto listed = known.find(c.path);
        if (listed == known.end()) {
            CHECK(match);
        } else {
            // A listed tape that now matches must leave kKnownDivergences.
            CHECK(!match);
            if (match) std::printf("  now matches, remove from kKnownDivergences: %s\n", c.path.c_str());
        }
    }
    // The order controls, every rule on: each must match unless listed in
    // kKnownDivergences.
    std::size_t controls_matched = 0;
    std::size_t control_tv_rows = 0;
    for (const OrderControl& control : kOrderControls) {
        Case c;
        c.path = control.path;
        c.bars = control.bars;
        c.tick = control.tick;
        c.step = control.step;
        listed_paths.insert(c.path);
        auto feed = feeds.find(c.bars);
        if (feed == feeds.end()) feed = feeds.emplace(c.bars, load_bars(c.bars)).first;
        const std::vector<Row> tv = tape_rows(c);
        control_tv_rows += tv.size();
        std::unique_ptr<source::PineStrategyHost> host = order_control_host(c.path, c.tick, c.step);
        CHECK(host != nullptr);
        if (!host) continue;
        const std::string difference = first_difference(tv, replay_control(*host, c, feed->second));
        const bool match = difference.empty();
        if (match) {
            ++controls_matched;
            std::printf("MATCH %s\n", c.path.c_str());
        } else {
            std::printf("DIFF %s %s\n", c.path.c_str(), difference.c_str());
        }
        if (known.count(c.path) == 0) {
            CHECK(match);
        } else {
            CHECK(!match);
            if (match) std::printf("  now matches, remove from kKnownDivergences: %s\n", c.path.c_str());
        }
    }
    CHECK(control_tv_rows == kOrderControlTvRows);
    std::printf("order controls: %zu/%zu match\n", controls_matched,
                sizeof(kOrderControls) / sizeof(kOrderControls[0]));
    for (const auto& [path, reason] : known) CHECK(listed_paths.count(path) == 1);
    CHECK(tv_rows == kTvRows);
    CHECK(recorded_tv_rows == kRecordedTvRows);

    std::printf("margin_call_rules: %zu/%zu tapes match, %zu TV rows\n", matched, asserted_tapes, tv_rows);
    std::printf("short cut-off gate, unpinned: %zu/%zu match\n", recorded_matched,
                recorded.size());

    switches = all_on;
    const std::set<std::string> all_on_matched = matching_tapes(cases, feeds);
    CHECK(all_on_matched.size() == matched);

    // The recorded tapes with pooc_fee_sizing off and on (every other switch
    // as shipped): report the tapes whose engine rows move. Nothing is
    // checked.
    {
        MarginRuleSwitches with_off = tree_defaults;
        MarginRuleSwitches with_on = tree_defaults;
        with_off.pooc_fee_sizing = false;
        with_on.pooc_fee_sizing = true;
        {
            std::size_t moved = 0;
            for (const Case* c : recorded) {
                const std::vector<Bar>& bars = feeds.at(c->bars);
                switches = with_off;
                const Outcome off = replay(*c, bars);
                switches = with_on;
                const Outcome on = replay(*c, bars);
                if (!same_rows(off, on)) {
                    ++moved;
                    std::printf("GAP-TOGGLE-MOVES %s\n", c->path.c_str());
                }
            }
            std::printf("short cut-off gate, pooc_fee_sizing off vs on: %zu/%zu tapes move\n", moved,
                        recorded.size());
        }
        switches = all_on;
    }

    // Ablation, over the asserted tapes, from every rule on: every switch is
    // load-bearing here -- off alone, it costs at least one tape that matches
    // with every rule on (gain_loss_money is pinned mainly by the
    // margin_ledger_rules tapes; these tapes book at most a few trades, yet
    // it and dust_unit_call each cost one) -- and with all of them off the
    // engine is back to the tapes it matched before the rules.
    const MarginRuleSwitches defaults = all_on;
    using S = pineforge::source::detail::MarginRuleSwitches;
    // load_bearing false: the rule's tapes live in another fixture
    // (margin_ledger_rules, admission_rules); off alone it may not cost one
    // of these, and must not gain one.
    const std::vector<Ablation> ablations = {
        {"decimal_sizing", &S::decimal_sizing},
        {"slipped_signal_admission", &S::slipped_signal_admission},
        {"unified_placement", &S::unified_placement, false},
        {"fill_price_recheck", &S::fill_price_recheck},
        {"close_first_admission", &S::close_first_admission, false},
        {"gain_loss_money", &S::gain_loss_money},
        {"dust_unit_call", &S::dust_unit_call},
        {"long_open_close_checks", &S::long_open_close_checks},
        {"negative_free_cash_call", &S::negative_free_cash_call},
        {"coof_next_point_close", &S::coof_next_point_close},
        {"close_point_reversal", &S::close_point_reversal},
        {"pooc_fee_sizing", &S::pooc_fee_sizing},
        {"point_fills_before_margin", &S::point_fills_before_margin, false},
        {"point_order_trailing_exits", &S::point_order_trailing_exits, false},
        {"pyramiding_ledger_records", &S::pyramiding_ledger_records, false},
        {"exit_child_tombstones", &S::exit_child_tombstones, false},
        {"tie_reversal_beside_exits", &S::tie_reversal_beside_exits, false},
    };
    CHECK(ablations.size() == sizeof(MarginRuleSwitches) / sizeof(bool));
    for (const auto& ablation : ablations) {
        switches = defaults;
        switches.*(ablation.flag) = false;
        const std::set<std::string> matched_off = matching_tapes(cases, feeds);
        const std::size_t off = matched_off.size();
        std::printf("ablation %s off: %zu/%zu tapes match\n", ablation.name, off, asserted_tapes);
        std::size_t lost = 0;
        for (const std::string& path : all_on_matched) lost += matched_off.count(path) == 0;
        for (const std::string& path : matched_off)
            if (all_on_matched.count(path) == 0)
                std::printf("  ablation %s off gains %s\n", ablation.name, path.c_str());
        if (ablation.load_bearing) {
            CHECK(lost > 0);
        } else {
            CHECK(off <= all_on_matched.size());
        }
    }
    // The schedule rules, off alone from every rule on: the gate, the path
    // points and the lagged follow-up are pinned by the short-cutoff-gate
    // tapes here, the close call's follow-up at the open by literal-21; the
    // others by tests/fixtures/margin_schedule_rules.
    using M = pineforge::source::detail::MarginScheduleSwitches;
    const std::vector<ScheduleAblation> schedule_ablations = {
        {"short_call_gate", &M::short_call_gate},
        {"short_path_points", &M::short_path_points},
        {"lagged_short_follow_up", &M::lagged_short_follow_up},
        {"pending_veto_first", &M::pending_veto_first, false},
        {"frozen_reversal_close", &M::frozen_reversal_close, false},
        {"add_signal_close", &M::add_signal_close, false},
        {"whole_share_lagged_follow_up", &M::whole_share_lagged_follow_up, false},
        {"long_call_gain_loss", &M::long_call_gain_loss, false},
        // Inside the opening-call schedule's shape (MarginOpeningSwitches)
        // the open's calls after the close-sized one replace it: literal-21
        // is pinned by booked_open_recheck and open_print_follow_up now.
        {"close_call_follow_up_at_open", &M::close_call_follow_up_at_open, false},
        // Pinned by tests/fixtures/margin_open_rules lots/.
        {"close_follow_up_after_script", &M::close_follow_up_after_script, false},
    };
    CHECK(schedule_ablations.size() == sizeof(MarginScheduleSwitches) / sizeof(bool));
    switches = defaults;
    for (const auto& ablation : schedule_ablations) {
        schedule = schedule_on;
        schedule.*(ablation.flag) = false;
        const std::set<std::string> matched_off = matching_tapes(cases, feeds);
        const std::size_t off = matched_off.size();
        std::printf("ablation %s off: %zu/%zu tapes match\n", ablation.name, off, asserted_tapes);
        std::size_t lost = 0;
        for (const std::string& path : all_on_matched) lost += matched_off.count(path) == 0;
        for (const std::string& path : matched_off)
            if (all_on_matched.count(path) == 0)
                std::printf("  ablation %s off gains %s\n", ablation.name, path.c_str());
        if (ablation.load_bearing) {
            CHECK(lost > 0);
        } else {
            CHECK(off <= all_on_matched.size());
        }
    }
    // The opening-call rules, off alone from every rule on: pinned by
    // tests/fixtures/margin_open_rules; here each may only cost tapes (the
    // fourteen source-close tapes of the short-s5 family, inherited/eth-slip-5
    // and schedule-q9p1305-s4 match with them on).
    using O = pineforge::source::detail::MarginOpeningSwitches;
    auto& opening = pineforge::source::detail::margin_opening_switches();
    const O opening_defaults = opening;
    const std::vector<std::pair<const char*, bool O::*>> opening_ablations = {
        {"close_sized_long_call", &O::close_sized_long_call},
        {"close_call_gate_at_print", &O::close_call_gate_at_print},
        {"booked_open_recheck", &O::booked_open_recheck},
        {"open_print_follow_up", &O::open_print_follow_up},
        {"open_check_after_add_fill", &O::open_check_after_add_fill},
        {"open_fill_admission", &O::open_fill_admission},
        {"whole_share_lagged_short", &O::whole_share_lagged_short},
        {"chained_follow_up", &O::chained_follow_up},
        {"short_point_drops_owed", &O::short_point_drops_owed},
        {"lot_by_lot_open_follow_up", &O::lot_by_lot_open_follow_up},
    };
    CHECK(opening_ablations.size() == sizeof(O) / sizeof(bool));
    schedule = schedule_on;
    switches = defaults;
    for (const auto& [name, flag] : opening_ablations) {
        opening = opening_defaults;
        opening.*flag = false;
        const std::set<std::string> matched_off = matching_tapes(cases, feeds);
        std::size_t lost = 0;
        for (const std::string& path : all_on_matched) lost += matched_off.count(path) == 0;
        std::printf("ablation %s off: %zu/%zu tapes match (%zu lost)\n", name, matched_off.size(),
                    asserted_tapes, lost);
        CHECK(matched_off.size() <= all_on_matched.size());
    }
    opening = opening_defaults;
    schedule = schedule_on;
    switches = defaults;
    for (const auto& ablation : ablations) switches.*(ablation.flag) = false;
    for (const auto& ablation : schedule_ablations) schedule.*(ablation.flag) = false;
    for (const auto& ablation : opening_ablations) opening.*(ablation.second) = false;
    const std::size_t all_off = matching_tapes(cases, feeds).size();
    std::printf("ablation all off: %zu/%zu tapes match\n", all_off, asserted_tapes);
    CHECK(all_off == kTapesBeforeRules);

    switches = tree_defaults;
    schedule = schedule_defaults;
    opening = opening_defaults;
    std::printf("\n%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed ? 1 : 0;
}
