/*
 * test_tv_money_precision.cpp — TradingView's broker carries money at TEN
 * SIGNIFICANT DIGITS (round 8 family R, OANDA:EURUSD@15; campaign notes
 * log-20260905t164404z-85800609 diagnosis, log-20260905t180248z-0dce5ab0
 * entry-leg admission, log-20260905t180249z-10358e84 margin-call trigger;
 * round 9 follow-up log-20260905t205824z-af397c83 and
 * log-20260905t210117z-ab914192, the whole-order drop band).
 *
 * The consequences pinned and implemented (engine.hpp tv_money_round /
 * tv_money_floor_lot / tv_money_scope, engine_fills.cpp fill-time gate and
 * tv_money_long_margin_call):
 *
 *   sizing      Q = floor_raw( sig10(E_s) / tick(close_S) / step ) x step,
 *               tick(close_S) = ticks x fl(mintick) as the broker holds it
 *   admission   a default 100 %-of-equity, margin-100 MARKET entry is
 *               DROPPED iff E_s < sig10(Q x tick(close_S)); a reversal keeps
 *               only its closing leg; this runs ahead of the exact fill check
 *   whole drop  past that, P = sig10( sig10(E_s) / Q ) < tick(close_S) drops
 *               the WHOLE order (a reversal keeps its position): a decimal tie
 *               at 1e-9 is decided by the ulp of the tick-built price
 *   margin call a margin-100 LONG is liquidated one contract at the first bar
 *               path point p where exact equity <= sig10(|Q| x p)
 *
 * The 203 lab tv capital sweeps of 2025-04-01 (scratch famr-adm-*: flat-{m,p},
 * FL, rev, revb, revc, revd, revL, S1, S1f, S2, S3, pS) are replayed on the
 * registry feed's bars (test_tv_money_precision_data.hpp, generated by
 * gen_tapes_v2.py) and compared ROW FOR ROW — entry bar, side, fill price,
 * quantity, exit bar, exit price, 'Margin call' vs close, net PnL. 202 tapes
 * are asserted (the 52 band tapes revb b06..b28, revd00..03, revL L24..L33,
 * S100..S103, S307..S317 among them); the 1 the generator's independent
 * predictor does not explain is the documented residual (revL L23: TV's
 * one-unit entry fill when the entry leg fails with Q == |position| + 1.00)
 * and is replayed for information only — it must never be silently
 * promoted. test_tv_money_band.cpp replays the famr3 sweeps that pinned the
 * band on other bars.
 */

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include <pineforge/bar.hpp>
#include <pineforge/engine.hpp>
#include <pineforge/source/pine_policy_support.hpp>
#include <pineforge/source/pine_strategy_host.hpp>
#include "oracle_fixture_config_shim.hpp"
#include "l4b_pending_projection_shim.hpp"

#include "test_tv_money_precision_data.hpp"

using namespace pineforge;
using pineforge::source::tv_money_floor_lot;
using pineforge::source::tv_money_round;
using namespace tv_money_tape_data;

static int tests_passed = 0;
static int tests_failed = 0;

#define CHECK(expr)                                                            \
    do {                                                                       \
        if (!(expr)) {                                                         \
            std::printf("  FAIL  %s:%d  %s\n", __FILE__, __LINE__, #expr);     \
            ++tests_failed;                                                    \
        } else {                                                               \
            ++tests_passed;                                                    \
        }                                                                      \
    } while (0)

static bool near(double a, double b, double tol = 1e-9) {
    return std::abs(a - b) <= tol;
}

namespace {

struct Row {
    int64_t entry_ts;
    bool is_long;
    double entry_price;
    double qty;
    int64_t exit_ts;
    double exit_price;
    int kind;   // 0 close, 1 margin call
    double pnl;
};

bool row_before(const Row& a, const Row& b) {
    if (a.entry_ts != b.entry_ts) return a.entry_ts < b.entry_ts;
    if (a.exit_ts != b.exit_ts) return a.exit_ts < b.exit_ts;
    return a.qty < b.qty;
}

std::vector<Bar> tape_bars() {
    std::vector<Bar> out;
    for (const BarRow& r : kBars) {
        Bar b;
        b.timestamp = r.ts;
        b.open = r.open; b.high = r.high; b.low = r.low; b.close = r.close;
        b.volume = 1.0;
        out.push_back(b);
    }
    return out;
}

// The sweeps' account: initial_capital as declared, percent_of_equity 100,
// commission 0, margin 100/100, OANDA:EURUSD (mintick 1e-5, lot 0.01),
// market fills at the next open, margin calls on.
class SweepProbe : public pineforge::source::PineStrategyHost {
public:
    SweepProbe(double capital, const Signal* signals, int n_signals)
        : signals_(signals), n_signals_(n_signals) {
        initial_capital_ = capital;
        default_qty_type_ = QtyType::PERCENT_OF_EQUITY;
        default_qty_value_ = 100.0;
        commission_type_ = CommissionType::PERCENT;
        commission_value_ = 0.0;
        margin_long_ = 100.0;
        margin_short_ = 100.0;
        pyramiding_ = 1;
        slippage_ = 0;
        syminfo_.pointvalue = 1.0;
        set_syminfo_mintick(0.00001);
        qty_step_ = 0.01;
        process_orders_on_close_ = false;
        set_margin_call_enabled(true);
    }
    void on_source_bar(const Bar& bar) override {
        for (int i = 0; i < n_signals_; ++i) {
            if (signals_[i].ts != bar.timestamp) continue;
            if (signals_[i].kind == 0) {
                strategy_close_all();
            } else {
                strategy_entry(i == 0 ? "A" : "B", signals_[i].kind > 0);
            }
        }
    }
    std::vector<Row> rows() const {
        std::vector<Row> out;
        for (const Trade& t : trades_) {
            out.push_back({t.entry_time, t.is_long, t.entry_price, t.qty,
                           t.exit_time, t.exit_price,
                           t.exit_comment == "Margin call" ? 1 : 0, t.pnl});
        }
        for (const Trade& t : range_end_trades_) {
            out.push_back({t.entry_time, t.is_long, t.entry_price, t.qty,
                           t.exit_time, t.exit_price, 2, t.pnl});
        }
        std::sort(out.begin(), out.end(), row_before);
        return out;
    }
    double frozen_qty_of_last_placement() const {
        return last_frozen_;
    }
    void set_step(double step) { qty_step_ = step; }
    using pineforge::source::PineStrategyHost::signed_position_size;
    using BacktestEngine::trade_count;
private:
    const Signal* signals_;
    int n_signals_;
    double last_frozen_ = std::numeric_limits<double>::quiet_NaN();
};

std::vector<Row> tape_rows(const Tape& t) {
    std::vector<Row> out;
    for (int i = 0; i < t.n_rows; ++i) {
        const TapeRow& r = t.rows[i];
        out.push_back({r.entry_ts, r.is_long, r.entry_price, r.qty, r.exit_ts,
                       r.exit_price, r.exit_kind, r.net_pnl});
    }
    std::sort(out.begin(), out.end(), row_before);
    return out;
}

void print_row(const char* tag, const Row& r) {
    std::printf("      %s %s entry %lld @ %.5f qty %.2f exit %lld @ %.5f kind %d pnl %.5f\n",
                tag, r.is_long ? "long " : "short", (long long)r.entry_ts,
                r.entry_price, r.qty, (long long)r.exit_ts, r.exit_price,
                r.kind, r.pnl);
}

// Row-for-row comparison; returns the mismatch count (size difference counts).
int rows_mismatch(const std::vector<Row>& got, const std::vector<Row>& want,
                  bool verbose) {
    int mismatches = got.size() != want.size() ? 1 : 0;
    const size_t n = std::min(got.size(), want.size());
    for (size_t i = 0; i < n; ++i) {
        const Row& g = got[i];
        const Row& w = want[i];
        const bool same =
            g.entry_ts == w.entry_ts && g.is_long == w.is_long
            && std::fabs(g.entry_price - w.entry_price) <= 1e-6
            && std::fabs(g.qty - w.qty) <= 1e-6
            && g.exit_ts == w.exit_ts
            && std::fabs(g.exit_price - w.exit_price) <= 1e-6
            && g.kind == w.kind
            && std::fabs(g.pnl - w.pnl) <= 5e-3;
        if (!same && verbose) {
            std::printf("    row %zu differs\n", i);
            print_row("engine", g);
            print_row("tape  ", w);
        }
        mismatches += !same;
    }
    if (verbose && got.size() != want.size()) {
        std::printf("    engine %zu rows, tape %zu rows\n", got.size(), want.size());
        for (size_t i = n; i < got.size(); ++i) print_row("engine+", got[i]);
        for (size_t i = n; i < want.size(); ++i) print_row("tape+  ", want[i]);
    }
    return mismatches;
}

}  // namespace

static void test_money_round() {
    std::printf("-- tv_money_round: ten significant digits, half-up --\n");
    CHECK(near(tv_money_round(998763.3420503), 998763.3421, 1e-12));
    CHECK(near(tv_money_round(998763.3420484), 998763.3420, 1e-12));
    CHECK(near(tv_money_round(998763.3425504), 998763.3426, 1e-12));
    CHECK(near(tv_money_round(998763.3425483), 998763.3425, 1e-12));
    CHECK(near(tv_money_round(1000000.0015396), 1000000.002, 1e-12));
    CHECK(near(tv_money_round(1000000.0014996), 1000000.001, 1e-12));
    CHECK(near(tv_money_round(1001239.6645078), 1001239.665, 1e-12));
    CHECK(near(tv_money_round(1001239.6644978), 1001239.664, 1e-12));
    CHECK(near(tv_money_round(948825.1787804), 948825.1788, 1e-12));
    CHECK(near(tv_money_round(948825.1787404), 948825.1787, 1e-12));
    CHECK(near(tv_money_round(-1234.4350144), -1234.435014, 1e-12));
    CHECK(tv_money_round(0.0) == 0.0);
}

// Every famr-adm tape, row for row, on the registry bars.
static void test_tape_replays() {
    std::printf("-- famr-adm-* capital sweeps: row-for-row replay on the 2025-04-01 bars --\n");
    const std::vector<Bar> bars = tape_bars();
    CHECK(bars.size() >= 17);
    int asserted = 0, asserted_ok = 0, residual = 0, residual_match = 0;
    std::vector<std::string> failed;
    for (const Tape& t : kTapes) {
        SweepProbe eng(t.capital, t.signals, t.n_signals);
        eng.run(bars.data(), bars.size());
        const std::vector<Row> got = eng.rows();
        const std::vector<Row> want = tape_rows(t);
        if (t.expect_match) {
            ++asserted;
            const int mm = rows_mismatch(got, want, /*verbose=*/true);
            if (mm == 0) ++asserted_ok; else failed.push_back(t.name);
            if (mm != 0) std::printf("   %s: %d row mismatch(es)\n", t.name, mm);
        } else {
            ++residual;
            const int mm = rows_mismatch(got, want, /*verbose=*/false);
            if (mm == 0) ++residual_match;
        }
    }
    std::printf("   asserted %d/%d tapes replay row for row; residual %d (%d happen to match): %s\n",
                asserted_ok, asserted, residual, residual_match,
                "the one-unit entry fill, not implemented");
    for (const std::string& f : failed) std::printf("   FAILED tape: %s\n", f.c_str());
    CHECK(asserted == 202);
    CHECK(asserted_ok == asserted);
    CHECK(residual == 1);
}

// Named pins on top of the replay (the rules stated on the numbers).
static void test_named_pins() {
    std::printf("-- named pins --\n");
    const std::vector<Bar> bars = tape_bars();
    auto find = [](const char* name) -> const Tape* {
        for (const Tape& t : kTapes) if (std::strcmp(t.name, name) == 0) return &t;
        return nullptr;
    };
    auto first_entry_qty = [&](const char* name, int64_t fill_ts) -> double {
        const Tape* t = find(name);
        if (t == nullptr) return -1.0;
        SweepProbe eng(t->capital, t->signals, t->n_signals);
        eng.run(bars.data(), bars.size());
        double q = 0.0;
        for (const Row& r : eng.rows()) if (r.entry_ts == fill_ts) q += r.qty;
        return q;
    };
    const int64_t fill1 = kBars[2].ts;   // 08:30Z open
    const int64_t fill2 = kBars[6].ts;   // 09:30Z open
    // Sizing from the ROUNDED equity: revc03 sizes the exact floor, revc04
    // (E 2e-6 higher, past the half unit) one lot more — which then fails the
    // rounded-cost admission, so its entry leg is dropped and only the close
    // leg fills (the tape).
    CHECK(near(first_entry_qty("famr-adm-revc-revc03", fill2), 922832.66, 1e-6));
    CHECK(near(first_entry_qty("famr-adm-revc-revc04", fill2), 0.0, 1e-6));
    // S2: the rounded equity lands one lot BELOW the exact floor.
    CHECK(near(first_entry_qty("famr-adm-S206", fill2), 925601.16, 1e-6));
    CHECK(near(first_entry_qty("famr-adm-S209", fill2), 925601.17, 1e-6));
    // Bare capital vs the rounded cost 1000000.002 (925120.73 x 1.08094).
    CHECK(near(first_entry_qty("famr-adm-revL-L05", fill1), 925120.72, 1e-6));  // C .0014996 -> .72
    CHECK(near(first_entry_qty("famr-adm-revL-L06", fill1), 0.0, 1e-6));        // .0015396 -> .73, dropped
    CHECK(near(first_entry_qty("famr-adm-revL-L17", fill1), 0.0, 1e-6));        // .0019796 dropped
    CHECK(near(first_entry_qty("famr-adm-FL02", fill1), 0.0, 1e-6));            // .0019980 dropped
    CHECK(near(first_entry_qty("famr-adm-revL-L18", fill1), 925120.73, 1e-6));  // .0020196 admitted
    CHECK(near(first_entry_qty("famr-adm-flat-p0000", fill1), 925000.0, 1e-6)); // C == cost: admitted
    // The one-contract margin call on a long in profit, at the first path
    // point where the exact equity is <= the rounded position value.
    {
        const Tape* t = find("famr-adm-revL-L18");
        SweepProbe eng(t->capital, t->signals, t->n_signals);
        eng.run(bars.data(), bars.size());
        bool one_unit_at_high = false;
        for (const Row& r : eng.rows()) {
            if (r.kind == 1 && r.is_long && near(r.qty, 1.0, 1e-9)
                && r.exit_ts == kBars[2].ts && near(r.exit_price, 1.08151, 1e-9)) {
                one_unit_at_high = true;
            }
        }
        CHECK(one_unit_at_high);
    }
    {
        const Tape* t = find("famr-adm-revL-L26");
        SweepProbe eng(t->capital, t->signals, t->n_signals);
        eng.run(bars.data(), bars.size());
        int long_margin_calls = 0;
        for (const Row& r : eng.rows()) if (r.kind == 1 && r.is_long) ++long_margin_calls;
        CHECK(long_margin_calls == 0);   // cash 0.00045 > every residual
    }
    // The whole-order drop band (rule 5): the long -> short reversal at the
    // 09:30Z open is dropped ENTIRELY — no short fills and the long is NOT
    // closed there (it runs to the close_all) — when sig10(sig10(E_s)/Q)
    // ties the sizing close as a decimal and the tick-built price sits one
    // ulp above double(close). revb b04/b05 just below the band are
    // close-only (the position exits at 09:30Z, no new entry), revb b06
    // opens the band, S100 is the 7-digit tie, revL L26 / S317 sit inside.
    auto second_decision = [&](const char* name) -> std::string {
        const Tape* t = find(name);
        if (t == nullptr) return "missing";
        SweepProbe eng(t->capital, t->signals, t->n_signals);
        eng.run(bars.data(), bars.size());
        // Side-agnostic: revb/S3 open short and reverse long, S1/revL/revd
        // open long and reverse short.
        double entry_qty = 0.0; bool position_exits_at_fill2 = false;
        for (const Row& r : eng.rows()) {
            if (r.entry_ts == fill2) entry_qty += r.qty;
            if (r.entry_ts < fill2 && r.exit_ts == fill2 && r.kind == 0) position_exits_at_fill2 = true;
        }
        if (entry_qty > 1.5) return "admit";
        if (entry_qty > 0.0) return "one-unit";
        return position_exits_at_fill2 ? "close-only" : "whole-drop";
    };
    CHECK(second_decision("famr-adm-revb-b05") == "close-only");
    CHECK(second_decision("famr-adm-revb-b06") == "whole-drop");
    CHECK(second_decision("famr-adm-revb-b28") == "whole-drop");
    CHECK(second_decision("famr-adm-S100") == "whole-drop");
    CHECK(second_decision("famr-adm-S103") == "whole-drop");
    CHECK(second_decision("famr-adm-revL-L26") == "whole-drop");
    CHECK(second_decision("famr-adm-revL-L33") == "whole-drop");
    CHECK(second_decision("famr-adm-S317") == "whole-drop");
    // tv_money_floor_lot: the everybar 1.085 placement — sig10(E) / tick(1.085)
    // = 918062.29999999992 floors to 918062.29 (TV filled 33222 + 884840.29),
    // where the nudged apply_qty_step would say 918062.30.
    {
        const double tick_1085 = std::floor(1.085 / 0.00001 + 0.5) * 0.00001;
        CHECK(tick_1085 > 1.085);   // fl(1e-5) carries the price one ulp up
        const double q = tv_money_round(996097.5955029) / tick_1085;
        CHECK(near(tv_money_floor_lot(q, 0.01), 918062.29, 1e-9));
        CHECK(near(std::floor(q / 0.01 + 1e-6) * 0.01, 918062.30, 1e-9));
    }
}

// Integer-lot / continuous instruments keep the exact arithmetic (scope).
static void test_out_of_scope_untouched() {
    std::printf("-- integer-lot / continuous instruments keep the exact arithmetic --\n");
    Signal sig[] = {{600000LL, 1}};
    std::vector<Bar> b;
    for (int i = 0; i < 3; ++i) {
        Bar bar; bar.open = bar.high = bar.low = bar.close = 100.0;
        bar.volume = 1.0; bar.timestamp = 600000LL * (i + 1);
        b.push_back(bar);
    }
    {
        SweepProbe p(10000.0015396, sig, 1);
        p.set_step(1.0);
        p.set_syminfo_mintick(0.01);
        p.run(b.data(), b.size());
        CHECK(near(p.signed_position_size(), 100.0, 1e-9));
    }
    {
        SweepProbe q(10000.0015396, sig, 1);
        q.set_step(0.0);
        q.set_syminfo_mintick(0.01);
        q.run(b.data(), b.size());
        CHECK(near(q.signed_position_size(), 100.000015396, 1e-9));
    }
}

int main() {
    test_money_round();
    test_tape_replays();
    test_named_pins();
    test_out_of_scope_untouched();
    std::printf("%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed == 0 ? 0 : 1;
}
