/*
 * test_tv_money_band.cpp — the whole-order drop band (round 9 family R
 * follow-up; campaign notes log-20260905t205824z-af397c83 and
 * log-20260905t210117z-ab914192): once the rounded-cost admission has passed,
 * TradingView's broker runs its fill-time margin check on the PRICE scale —
 * P = sig10( sig10(E_s) / Q ) must reach the sizing price as the broker
 * holds it, tick(close_S) = ticks x fl(mintick); P < tick(close_S) drops
 * the WHOLE default market order (a reversal keeps its position, close leg
 * included). A decimal tie at 1e-9 is decided by the ulp of the tick-built
 * price (engine.hpp rule 5, engine_fills.cpp fill-time gate).
 *
 * The famr3 lab tv sweeps that pinned it (OANDA:EURUSD 15, 2025-03-31..
 * 04-04; scratch /tmp/famr3: F6 — 153 bare-capital longs at C =
 * sig10(cost) + 0.0002 (6-digit money), F7 — 81 seven-digit ties, F6h — 153
 * at + 0.0006, T — 27 long->short pairs, A/B/R1/R2 — the taro probe's own
 * states as two-signal scripts) are replayed on the registry feed's bars
 * (test_tv_money_band_data.hpp, generated by gen_famr3.py) and compared ROW
 * FOR ROW — entry bar, side, fill price, quantity, exit bar, exit price,
 * 'Margin call' vs close, net PnL. The generator's independent Python
 * predictor explains every decision of all 448 tapes (507 decisions: 97 + 2
 * bare-capital drops, 12 whole-dropped reversals, 2 close-only, the rest
 * admitted); 445 are asserted row for row. The 3 residual tapes
 * (F6-010630, F6-032300, F6-310930) carry a DIFFERENT, documented
 * TradingView artifact outside this pin: the rule-3 one-contract trim fires
 * on the same bar whose close issues strategy.close_all, and TV's close_all
 * still closes the PRE-trim quantity, leaving a 1-unit opposite lot open to
 * the range end (the family-S 'close artifact lot' shape). They are replayed
 * for information only and must never be silently promoted.
 */

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include <pineforge/bar.hpp>
#include <pineforge/engine.hpp>
#include <pineforge/source/pine_strategy_host.hpp>
#include "oracle_fixture_config_shim.hpp"

#include "test_tv_money_band_data.hpp"

using namespace pineforge;
using namespace tv_money_band_data;

static int tests_passed = 0;
static int tests_failed = 0;

#define CHECK(expr)                                                            \
    do {                                                                       \
        if (!(expr)) {                                                         \
            std::printf("  FAIL  %s:%d  %s\n", __FILE__, __LINE__, #expr);     \
            ++tests_failed;                                                    \
        } else {                                                               \
            ++tests_passed;                                                    \
        }                                                                      \
    } while (0)

namespace {

struct Row {
    int64_t entry_ts;
    bool is_long;
    double entry_price;
    double qty;
    int64_t exit_ts;
    double exit_price;
    int kind;   // 0 close, 1 margin call, 2 range end
    double pnl;
};

bool row_before(const Row& a, const Row& b) {
    if (a.entry_ts != b.entry_ts) return a.entry_ts < b.entry_ts;
    if (a.exit_ts != b.exit_ts) return a.exit_ts < b.exit_ts;
    return a.qty < b.qty;
}

std::vector<Bar> tape_bars() {
    std::vector<Bar> out;
    for (const BarRow& r : kBars) {
        Bar b;
        b.timestamp = r.ts;
        b.open = r.open; b.high = r.high; b.low = r.low; b.close = r.close;
        b.volume = 1.0;
        out.push_back(b);
    }
    return out;
}

// The sweeps' account: initial_capital as declared, percent_of_equity 100,
// commission 0, margin 100/100, OANDA:EURUSD (mintick 1e-5, lot 0.01),
// market fills at the next open, margin calls on.
class SweepProbe : public pineforge::source::PineStrategyHost {
public:
    SweepProbe(double capital, const Signal* signals, int n_signals)
        : signals_(signals), n_signals_(n_signals) {
        initial_capital_ = capital;
        default_qty_type_ = QtyType::PERCENT_OF_EQUITY;
        default_qty_value_ = 100.0;
        commission_type_ = CommissionType::PERCENT;
        commission_value_ = 0.0;
        margin_long_ = 100.0;
        margin_short_ = 100.0;
        pyramiding_ = 1;
        slippage_ = 0;
        syminfo_.pointvalue = 1.0;
        set_syminfo_mintick(0.00001);
        qty_step_ = 0.01;
        process_orders_on_close_ = false;
        set_margin_call_enabled(true);
    }
    void on_source_bar(const Bar& bar) override {
        for (int i = 0; i < n_signals_; ++i) {
            if (signals_[i].ts != bar.timestamp) continue;
            if (signals_[i].kind == 0) {
                strategy_close_all();
            } else {
                strategy_entry(i == 0 ? "A" : "B", signals_[i].kind > 0);
            }
        }
    }
    std::vector<Row> rows() const {
        std::vector<Row> out;
        for (const Trade& t : trades_) {
            out.push_back({t.entry_time, t.is_long, t.entry_price, t.qty,
                           t.exit_time, t.exit_price,
                           t.exit_comment == "Margin call" ? 1 : 0, t.pnl});
        }
        for (const Trade& t : range_end_trades_) {
            out.push_back({t.entry_time, t.is_long, t.entry_price, t.qty,
                           t.exit_time, t.exit_price, 2, t.pnl});
        }
        std::sort(out.begin(), out.end(), row_before);
        return out;
    }
private:
    const Signal* signals_;
    int n_signals_;
};

std::vector<Row> tape_rows(const Tape& t) {
    std::vector<Row> out;
    for (int i = 0; i < t.n_rows; ++i) {
        const TapeRow& r = t.rows[i];
        out.push_back({r.entry_ts, r.is_long, r.entry_price, r.qty, r.exit_ts,
                       r.exit_price, r.exit_kind, r.net_pnl});
    }
    std::sort(out.begin(), out.end(), row_before);
    return out;
}

void print_row(const char* tag, const Row& r) {
    std::printf("      %s %s entry %lld @ %.5f qty %.2f exit %lld @ %.5f kind %d pnl %.5f\n",
                tag, r.is_long ? "long " : "short", (long long)r.entry_ts,
                r.entry_price, r.qty, (long long)r.exit_ts, r.exit_price,
                r.kind, r.pnl);
}

int rows_mismatch(const std::vector<Row>& got, const std::vector<Row>& want,
                  bool verbose) {
    int mismatches = got.size() != want.size() ? 1 : 0;
    const size_t n = std::min(got.size(), want.size());
    for (size_t i = 0; i < n; ++i) {
        const Row& g = got[i];
        const Row& w = want[i];
        const bool same =
            g.entry_ts == w.entry_ts && g.is_long == w.is_long
            && std::fabs(g.entry_price - w.entry_price) <= 1e-6
            && std::fabs(g.qty - w.qty) <= 1e-6
            && g.exit_ts == w.exit_ts
            && std::fabs(g.exit_price - w.exit_price) <= 1e-6
            && g.kind == w.kind
            && std::fabs(g.pnl - w.pnl) <= 5e-3;
        if (!same && verbose) {
            std::printf("    row %zu differs\n", i);
            print_row("engine", g);
            print_row("tape  ", w);
        }
        mismatches += !same;
    }
    if (verbose && got.size() != want.size()) {
        std::printf("    engine %zu rows, tape %zu rows\n", got.size(), want.size());
        for (size_t i = n; i < got.size(); ++i) print_row("engine+", got[i]);
        for (size_t i = n; i < want.size(); ++i) print_row("tape+  ", want[i]);
    }
    return mismatches;
}

const Tape* find_tape(const char* name) {
    for (const Tape& t : kTapes) if (std::strcmp(t.name, name) == 0) return &t;
    return nullptr;
}

// The first decision of a tape: qty filled at the first signal's next open.
double first_entry_qty(const std::vector<Bar>& bars, const char* name) {
    const Tape* t = find_tape(name);
    if (t == nullptr) return -1.0;
    SweepProbe eng(t->capital, t->signals, t->n_signals);
    eng.run(bars.data(), bars.size());
    double q = 0.0;
    int64_t fill = 0;
    for (size_t i = 0; i + 1 < bars.size(); ++i) {
        if (bars[i].timestamp == t->signals[0].ts) fill = bars[i + 1].timestamp;
    }
    for (const Row& r : eng.rows()) if (r.entry_ts == fill) q += r.qty;
    return q;
}

}  // namespace

static void test_band_replays() {
    std::printf("-- famr3-* sweeps: row-for-row replay on the 2025-03-31..04-04 bars --\n");
    const std::vector<Bar> bars = tape_bars();
    CHECK(bars.size() >= 400);
    int asserted = 0, asserted_ok = 0, residual = 0, residual_match = 0;
    std::vector<std::string> failed;
    for (const Tape& t : kTapes) {
        SweepProbe eng(t.capital, t.signals, t.n_signals);
        eng.run(bars.data(), bars.size());
        const std::vector<Row> got = eng.rows();
        const std::vector<Row> want = tape_rows(t);
        if (t.expect_match) {
            ++asserted;
            const int mm = rows_mismatch(got, want, /*verbose=*/true);
            if (mm == 0) ++asserted_ok; else failed.push_back(t.name);
            if (mm != 0) std::printf("   %s (%s): %d row mismatch(es)\n", t.name, t.reason, mm);
        } else {
            ++residual;
            const int mm = rows_mismatch(got, want, /*verbose=*/false);
            if (mm == 0) ++residual_match;
        }
    }
    std::printf("   asserted %d/%d tapes replay row for row; residual %d (%d happen to match)\n",
                asserted_ok, asserted, residual, residual_match);
    for (const std::string& f : failed) std::printf("   FAILED tape: %s\n", f.c_str());
    CHECK(asserted == 445);
    CHECK(asserted_ok == asserted);
    CHECK(residual == 3);
}

// The rule stated on the numbers: same sig10(E) - sig10(cost) = +0.0002,
// bare capital, a pure function of the close.
static void test_named_pins() {
    std::printf("-- named pins --\n");
    const std::vector<Bar> bars = tape_bars();
    // double(1.08273) sits 3.0e-17 below its decimal: the tick product is one
    // ulp above, P == 1.08273 as a decimal -> P < tick(close) -> DROPPED.
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6-010400")) < 1e-9);
    // double(1.08254) sits 2.1e-17 below: the product rounds back to the same
    // double, P == tick(close) -> FILLED (923753.39), then the one-contract
    // margin call of rule 3 at the 04:15Z bar's 1.08282.
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6-010330") - 923753.39) < 1e-6);
    // 7-digit ties: 1.08266 drops at sig10(cost) - cost = +0.00004 (F6) but
    // fills at +0.000466 (F7: P rounds UP to 1.082660001 > tick(close)).
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6-311130")) < 1e-9);
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F7-311130") - 923651.93) < 1e-6);
    // sig10(E) = sig10(cost) + 0.0006 (F6h): P = close + 1e-9 everywhere -> filled.
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6h-041630") - 911643.51) < 1e-6);
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6-041630")) < 1e-9);
    // double(1.08226) is 2.1e-19 below its decimal — inside the 2.2e-17
    // margin the fl(1e-5) product leaves: filled.
    CHECK(std::fabs(first_entry_qty(bars, "famr3-F6-310800") - 923992.38) < 1e-6);
}

int main() {
    test_band_replays();
    test_named_pins();
    std::printf("%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed == 0 ? 0 : 1;
}
