// L4f switched-route witnesses for request.security routing and sampled fills.
//
// H11 source literal: data/3commas-3commas-triple-rsi-dca-long-risk-adjusted-
// averaging-strategy registers 15/30/5 request.security evaluators on a 15m
// chart, including the 5m lookahead_on shape.  H12/H15 use the observed
// NYSE:F split-feed and COOF routing shapes.  H05 preserves the legacy
// directional tick result (1804.94) on both the ordinary and magnifier paths.

#include <pineforge/source/pine_adapter.hpp>
#include <pineforge/source/pine_strategy_host.hpp>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <limits>
#include <string>
#include <vector>

using namespace pineforge;

#define CHECK(condition)                                                       \
    do {                                                                       \
        if (!(condition)) {                                                    \
            std::fprintf(stderr, "CHECK failed at %s:%d: %s\\n",             \
                         __FILE__, __LINE__, #condition);                      \
            std::abort();                                                       \
        }                                                                      \
    } while (0)

namespace {

constexpr std::int64_t kQuarter = 15 * 60 * 1000;
constexpr std::int64_t kDay = 24 * 60 * 60 * 1000;

class H11Probe final : public source::PineStrategyHost {
public:
    int source_callbacks = 0;
    int lower_tf_completions = 0;

    void configure_security_evaluators() override {
        security_eval_states_.clear();
        // Generated by the H11 probe: entryTF=15, so1TF=30, so2TF=5.
        register_security_eval(0, "15", input_tf_, true, false);
        register_security_eval(1, "30", input_tf_, true, false);
        register_security_eval(2, "5", input_tf_, true, false);
    }

    void evaluate_security(int sec_id, const Bar&, bool is_complete) override {
        if (sec_id == 2 && is_complete) ++lower_tf_completions;
    }

    void on_source_bar(const Bar&) override { ++source_callbacks; }
};

class H12Probe final : public source::PineStrategyHost {
public:
    int source_callbacks = 0;

    void configure_security_evaluators() override {
        security_eval_states_.clear();
        // Generated by the H12 probe: request.security(..., "5", ..., off).
        register_security_eval(0, "5", input_tf_, false, false);
    }

    void on_source_bar(const Bar&) override { ++source_callbacks; }
};

class H15Probe final : public source::PineStrategyHost {
public:
    int source_callbacks = 0;

    void configure_security_evaluators() override {
        security_eval_states_.clear();
        register_security_eval(0, "240", input_tf_, false, false);
    }

    void on_source_bar(const Bar&) override {
        if (source_callbacks == 0) strategy_entry("Long", true, 0.0, 0.0, 1.0);
        ++source_callbacks;
    }
};

class H05StopProbe final : public source::PineStrategyHost {
public:
    void on_source_bar(const Bar& bar) override {
        if (bar.timestamp != 1743420600000LL) return;
        strategy_entry("L", true, std::numeric_limits<double>::quiet_NaN(),
                       std::numeric_limits<double>::quiet_NaN(), 1.0);
        // The H05 ENDPOINTS probe's entry-bar literal:
        // 1801.93 + (1807.96 - 1801.93) / 2 == 1804.945.
        strategy_exit("X", "L", std::numeric_limits<double>::quiet_NaN(), 1804.945,
                      std::numeric_limits<double>::quiet_NaN(),
                      std::numeric_limits<double>::quiet_NaN(),
                      std::numeric_limits<double>::quiet_NaN(), 100.0);
    }
};

class H05SlippageProbe final : public source::PineStrategyHost {
public:
    int source_callbacks = 0;

    void on_source_bar(const Bar&) override {
        if (source_callbacks == 0) {
            // Default sizing reaches HostSized and must receive slippage once.
            strategy_entry("Zenith Long", true);
        } else if (source_callbacks == 1) {
            strategy_close("Zenith Long");
        }
        ++source_callbacks;
    }
};

std::vector<Bar> h05_bars() {
    return {
        {1801.93, 1807.96, 1800.92, 1806.37, 37418.258, 1743420600000LL},
        {1806.37, 1819.00, 1805.97, 1812.52, 92807.927, 1743421500000LL},
        {1822.93, 1825.64, 1792.60, 1803.91, 256839.71, 1743427800000LL},
    };
}

void test_h11_plain_request_security_ltf_is_refused_at_validation() {
    H11Probe probe;
    const Bar bars[] = {
        {1855.88, 1862.18, 1854.03, 1859.99, 46681.148, 1743571800000LL},
        {1859.99, 1863.69, 1854.10, 1855.08, 53916.625, 1743572700000LL},
    };
    probe.run(bars, 2, "15", "15", false, 4, MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().find(
        "Use request.security_lower_tf for sub-input timeframes") != std::string::npos);
    CHECK(probe.source_callbacks == 0);
    CHECK(probe.lower_tf_completions == 0);
}

void test_h12_uncovered_auxiliary_chart_slot_is_a_gap_not_a_refusal() {
    // NYSE:F's 2021-11-26 early close has chart labels 17:45 and 18:00Z;
    // the 1m feed has the former but not the latter. This is the first gap in
    // the pinned H12 lane feed, which must not prevent its 2025-26 probe range.
    constexpr std::int64_t first = 1637948700000LL;
    const Bar chart[] = {
        {12.90, 12.94, 12.86, 12.91, 100.0, first},
        {12.91, 12.92, 12.88, 12.90, 100.0, first + kQuarter},
    };
    const Bar aux[] = {
        {12.90, 12.91, 12.89, 12.91, 10.0, first},
    };
    H12Probe probe;
    probe.set_syminfo_timezone("America/New_York");
    probe.set_syminfo_session("0930-1600");
    probe.set_syminfo_type("stock");
    CHECK(probe.set_aux_security_feed(aux, 1, "1"));
    probe.run(chart, 2, "15", "15", false, 4, MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    CHECK(probe.source_callbacks == 2);
}

void test_h15_coof_uses_the_native_chart_coordinate_for_auxiliary_routing() {
    const Bar chart[] = {
        {100.0, 101.0, 99.0, 100.0, 10.0, 1743465600000LL},
        {100.0, 101.0, 99.0, 100.0, 10.0, 1743465600000LL + kDay},
        {100.0, 101.0, 99.0, 100.0, 10.0, 1743465600000LL + 2 * kDay},
    };
    const Bar aux[] = {
        {100.0, 100.0, 100.0, 100.0, 1.0, 1743465600000LL},
        {100.0, 100.0, 100.0, 100.0, 1.0, 1743465600000LL + kDay},
        {100.0, 100.0, 100.0, 100.0, 1.0, 1743465600000LL + 2 * kDay},
    };
    H15Probe probe;
    source::PineStrategyConfig config;
    config.calc_on_order_fills = true;
    config.default_qty_type = static_cast<int>(QtyType::FIXED);
    config.default_qty_value = 1.0;
    probe.configure_pine_strategy(config);
    probe.set_syminfo_timezone("UTC");
    probe.set_syminfo_session("24x7");
    probe.set_syminfo_type("crypto");
    CHECK(probe.set_aux_security_feed(aux, 3, "1"));
    probe.run(chart, 3, "1D", "1D", false, 4, MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    CHECK(probe.source_callbacks == 3);
}

void test_h05_trigger_level_uses_legacy_directional_tick_price() {
    H05StopProbe probe;
    auto bars = h05_bars();
    probe.set_syminfo_mintick(0.01);
    // Continuous matching selects the level, just as the legacy OHLC path
    // did before its directional sell-side tick projection.
    probe.run(bars.data(), static_cast<int>(bars.size()), "15", "15", false, 4,
              MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    CHECK(probe.trade_count() == 1);
    CHECK(std::abs(probe.get_trade(0).exit_price - 1804.94) < 1e-9);
}

void test_h05_sampled_path_cross_books_the_stop_level() {
    H05StopProbe probe;
    auto bars = h05_bars();
    probe.set_syminfo_mintick(0.01);
    // ab9714be pine_scheduler.cpp:911-916: the script-bar open 1822.93 is
    // not through 1804.945, so the 1792.60 ENDPOINTS low is a path cross
    // at the stop (1804.94), not a one-price gap at the sample.
    probe.run(bars.data(), static_cast<int>(bars.size()), "15", "15", true, 4,
              MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    CHECK(probe.trade_count() == 1);
    CHECK(std::abs(probe.get_trade(0).exit_price - 1804.94) < 1e-9);
}

void test_h05_host_sized_market_slippage_is_applied_once() {
    H05SlippageProbe probe;
    source::PineStrategyConfig config;
    config.default_qty_type = static_cast<int>(QtyType::FIXED);
    config.default_qty_value = 1.0;
    config.slippage = 1;
    probe.configure_pine_strategy(config);
    probe.set_syminfo_mintick(0.01);
    const Bar bars[] = {
        {100.0, 100.0, 100.0, 100.0, 1.0, 1000},
        {100.0, 100.0, 100.0, 100.0, 1.0, 2000},
        {100.0, 100.0, 100.0, 100.0, 1.0, 3000},
    };
    probe.run(bars, 3, "1", "1", false, 4, MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    CHECK(probe.trade_count() == 1);
    CHECK(std::abs(probe.get_trade(0).entry_price - 100.01) < 1e-9);
    CHECK(std::abs(probe.get_trade(0).exit_price - 99.99) < 1e-9);
}

void test_h05_source_projection_uses_legacy_volume_weighted_cap() {
    class Noop final : public source::PineStrategyHost {
    public:
        void on_source_bar(const Bar&) override {}
    } probe;
    probe.set_magnifier_volume_weighted(true);
    const Bar bars[] = {
        {100.0, 101.0, 99.0, 100.0, 1.0, 1000},
        {100.0, 101.0, 99.0, 100.0, 1.0, 2000},
    };
    probe.run(bars, 2, "15", "15", true, 20, MagnifierDistribution::ENDPOINTS);
    CHECK(probe.last_error().empty());
    const NativeStateView state = probe.native_state();
    const IntrabarPath::synthesized* path = state.spec
        ? state.spec->intrabar.synthesized_path() : nullptr;
    CHECK(path != nullptr);
    CHECK(path->volume_weighted_min_samples == 2);
    CHECK(path->volume_weighted_max_samples == 80);
}

} // namespace

int main() {
    test_h11_plain_request_security_ltf_is_refused_at_validation();
    test_h12_uncovered_auxiliary_chart_slot_is_a_gap_not_a_refusal();
    test_h15_coof_uses_the_native_chart_coordinate_for_auxiliary_routing();
    test_h05_trigger_level_uses_legacy_directional_tick_price();
    test_h05_sampled_path_cross_books_the_stop_level();
    test_h05_host_sized_market_slippage_is_applied_once();
    test_h05_source_projection_uses_legacy_volume_weighted_cap();
    std::puts("test_l4f_security_magnifier: OK");
    return 0;
}
