/*
 * test_margin_ledger_rules_tapes.cpp -- margin, sizing and admission rules on
 * TradingView's tapes of event-ledger probes.
 *
 * tests/fixtures/margin_ledger_rules holds 381 `lab tv` tapes of 165
 * synthetic probes (README.md there): each probe's script issues a ledger of
 * strategy.entry / strategy.close / strategy.close_all calls at fixed bars --
 * explicit quantities or the default 100 % of equity -- on NYSE:F (15 minutes
 * and 1 day), NASDAQ:AAPL and BINANCE:ETHUSDT.P (15 minutes), at margin 100
 * or 0, with no commission and no slippage. The last entry before the final
 * close_all is the boundary order; an `after_close` probe also issues
 * strategy.close("Seed") right after it. cases.tsv (generated by
 * build_cases.py from each probe's plan.json) lists one row per tape.
 *
 * Each row is replayed through the Pine adapter on every bar of its chart's
 * exported window (bars/, from 00:00 UTC through to 00:00 UTC inclusive): a
 * handwritten host issues the plan's calls on the bar opening at their time,
 * in the script's statement order. Every trade row TradingView reports -- its
 * closed trades and a position still open at the range end, which
 * TradingView lists as a trade closed at the last bar's close -- must be the
 * engine's report row at the same index: side, quantity in lots, entry and
 * exit price in ticks, entry and exit time, and the row count. PnL and the
 * Signal column are not compared. The range-end rows come from the host
 * itself (report_trade_count() / get_report_trade()).
 *
 * The tree ships every margin rule switch
 * (pineforge::source::detail::MarginRuleSwitches) on, which this test
 * checks; the pass runs with the shipped switches. kKnownDivergences names
 * the tapes the engine is known not to reproduce yet: every unlisted tape
 * must match and every listed tape must still differ, so the list shrinks as
 * the engine learns a rule. The two admission halves are then turned off one
 * at a time, and each must cost tapes.
 */

#include <pineforge/bar.hpp>
#include <pineforge/source/pine_adapter.hpp>
#include <pineforge/source/pine_strategy_host.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <fstream>
#include <limits>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

using namespace pineforge;

static int tests_passed = 0;
static int tests_failed = 0;

#define CHECK(expr)                                                            \
    do {                                                                       \
        if (!(expr)) {                                                         \
            std::printf("  FAIL  %s:%d  %s\n", __FILE__, __LINE__, #expr);     \
            ++tests_failed;                                                    \
        } else {                                                               \
            ++tests_passed;                                                    \
        }                                                                      \
    } while (0)

#ifndef PINEFORGE_MARGIN_LEDGER_RULES_FIXTURE_DIR
#error "PINEFORGE_MARGIN_LEDGER_RULES_FIXTURE_DIR must name tests/fixtures/margin_ledger_rules"
#endif

namespace {

constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();
constexpr std::int64_t kMinute = 60'000;
constexpr std::size_t kTapes = 381;
constexpr std::size_t kTvRows = 43088;

// Why a tape is not reproduced yet, one line per kind. The probe's boundary
// order is "Turn": a reversal against the held "Seed" or ledger position, or
// an entry from flat.
// Tapes the engine does not reproduce yet: fixture tape directory and its
// reason. A listed tape that starts matching fails the test until its entry
// is removed.
const char kHistoryResidual[] = "G+L residual call: history regime unpinned";
const std::vector<std::pair<std::string, std::string>> kKnownDivergences = {
    // The residual call on a history: these proozac ledgers need the 1x long
    // residual call on the G + L cash after their trade history, which the
    // tree keeps in its earlier scope (net profit with no tracked roundoff).
    {"proozac-history-k0-after-v2/r1", kHistoryResidual},
    {"proozac-history-k0-after/r1", kHistoryResidual},
    {"proozac-history-k0-only-v2-ledger-witness/r1", kHistoryResidual},
    {"proozac-history-k0-only-v2-ledger-witness/r2", kHistoryResidual},
    {"proozac-history-k0-only-v2-ledger-witness/r3", kHistoryResidual},
    {"proozac-history-k0-only-v2-ledger-witness/r4", kHistoryResidual},
    {"proozac-history-k0-only-v2/r1", kHistoryResidual},
    {"proozac-history-k0-only/r1", kHistoryResidual},
};

std::string fixture(const std::string& relative) {
    return std::string(PINEFORGE_MARGIN_LEDGER_RULES_FIXTURE_DIR) + "/" + relative;
}

std::vector<std::string> split(const std::string& text, char separator) {
    std::vector<std::string> cells;
    std::string cell;
    std::istringstream fields(text);
    while (std::getline(fields, cell, separator)) cells.push_back(cell);
    if (!text.empty() && text.back() == separator) cells.emplace_back();
    return cells;
}

std::int64_t days_from_civil(int y, unsigned m, unsigned d) {
    y -= m <= 2;
    const int era = (y >= 0 ? y : y - 399) / 400;
    const unsigned yoe = static_cast<unsigned>(y - era * 400);
    const unsigned doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return static_cast<std::int64_t>(era) * 146097 + static_cast<std::int64_t>(doe) - 719468;
}

// A tape stamp "YYYY-MM-DD HH:MM" rendered at UTC+8 -> UTC milliseconds.
std::int64_t tape_ms(const std::string& stamp) {
    int y = 0, mo = 0, d = 0, h = 0, mi = 0;
    if (std::sscanf(stamp.c_str(), "%d-%d-%d %d:%d", &y, &mo, &d, &h, &mi) != 5) return -1;
    const std::int64_t days = days_from_civil(y, static_cast<unsigned>(mo),
                                              static_cast<unsigned>(d));
    return ((days * 24 + h - 8) * 60 + mi) * kMinute;
}

enum class Op { Entry, Close, CloseAll };

// One scripted call: strategy.entry(id, side, qty) -- qty NaN for the
// default quantity --, strategy.close(id) or strategy.close_all().
struct Event {
    std::int64_t time = 0;
    Op op = Op::Entry;
    std::string id;
    bool is_long = true;
    double qty = kNaN;
    bool boundary = false;
};

struct Case {
    std::string name;
    std::string path;  // the tape's directory, <name>/<rK>
    std::string tape;
    std::string bars;
    std::string symbol;
    std::string timeframe;
    double tick = 0.0;
    double step = 0.0;
    double capital = 0.0;
    double margin_long = 100.0;
    double margin_short = 100.0;
    bool after_close = false;
    std::vector<Event> events;
};

std::vector<Case> load_cases() {
    std::ifstream in(fixture("cases.tsv"));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    std::map<std::string, std::size_t> column;
    const std::vector<std::string> header = split(line, '\t');
    for (std::size_t i = 0; i < header.size(); ++i) column[header[i]] = i;
    for (const char* name : {"name", "tape", "bars", "symbol", "timeframe", "tick", "step", "capital",
                             "margin_long", "margin_short", "after_close", "events"}) {
        CHECK(column.count(name) == 1);
        if (!column.count(name)) return {};
    }
    std::vector<Case> cases;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        const std::vector<std::string> cell = split(line, '\t');
        CHECK(cell.size() == header.size());
        if (cell.size() != header.size()) continue;
        auto at = [&](const char* name) -> const std::string& { return cell[column[name]]; };
        auto number = [&](const char* name) { return std::strtod(at(name).c_str(), nullptr); };
        Case c;
        c.name = at("name");
        c.tape = at("tape");
        const std::string suffix = "/tv_trades.csv";
        CHECK(c.tape.size() > suffix.size() &&
              c.tape.compare(c.tape.size() - suffix.size(), suffix.size(), suffix) == 0);
        c.path = c.tape.substr(0, c.tape.size() - suffix.size());
        c.bars = at("bars");
        c.symbol = at("symbol");
        c.timeframe = at("timeframe");
        CHECK(c.timeframe == "15" || c.timeframe == "1D");
        c.tick = number("tick");
        c.step = number("step");
        c.capital = number("capital");
        c.margin_long = number("margin_long");
        c.margin_short = number("margin_short");
        c.after_close = at("after_close") == "1";
        for (const std::string& text : split(at("events"), ';')) {
            // time:op:id:side:qty:boundary
            const std::vector<std::string> part = split(text, ':');
            CHECK(part.size() == 6);
            if (part.size() != 6) continue;
            Event event;
            event.time = static_cast<std::int64_t>(std::strtoll(part[0].c_str(), nullptr, 10));
            CHECK(part[1] == "entry" || part[1] == "close" || part[1] == "close_all");
            event.op = part[1] == "entry" ? Op::Entry : part[1] == "close" ? Op::Close : Op::CloseAll;
            event.id = part[2];
            event.is_long = part[3] == "1";
            if (event.op == Op::Entry) CHECK(part[3] == "1" || part[3] == "-1");
            if (!part[4].empty()) event.qty = std::strtod(part[4].c_str(), nullptr);
            event.boundary = part[5] == "1";
            c.events.push_back(std::move(event));
        }
        CHECK(!c.events.empty());
        cases.push_back(std::move(c));
    }
    return cases;
}

// Every row of a bars/ file: the chart's window, from 00:00 UTC through to
// 00:00 UTC inclusive.
std::vector<Bar> load_bars(const std::string& name) {
    std::ifstream in(fixture("bars/" + name));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    CHECK(line == "timestamp,open,high,low,close,volume");
    std::vector<Bar> bars;
    while (std::getline(in, line)) {
        const std::vector<std::string> cell = split(line, ',');
        CHECK(cell.size() == 6);
        if (cell.size() != 6) continue;
        bars.push_back({std::strtod(cell[1].c_str(), nullptr), std::strtod(cell[2].c_str(), nullptr),
                        std::strtod(cell[3].c_str(), nullptr), std::strtod(cell[4].c_str(), nullptr),
                        std::strtod(cell[5].c_str(), nullptr),
                        static_cast<std::int64_t>(std::strtoll(cell[0].c_str(), nullptr, 10))});
    }
    return bars;
}

// One trade row as both sides report it: prices in ticks, quantity in lots.
struct Row {
    bool is_long = true;
    long long qty_lots = 0;
    long long entry_ticks = 0;
    long long exit_ticks = 0;
    std::int64_t entry_ms = 0;
    std::int64_t exit_ms = 0;
};

Row make_row(bool is_long, double qty, double entry_price, double exit_price,
             std::int64_t entry_ms, std::int64_t exit_ms, const Case& c) {
    return {is_long, std::llround(qty / c.step), std::llround(entry_price / c.tick),
            std::llround(exit_price / c.tick), entry_ms, exit_ms};
}

// TradingView's rows: each Exit row paired with the Entry row of its trade
// number, in trade-number order. tv_trades.csv starts with a UTF-8 BOM; its
// header is "Trade number,Type,Date and time,Signal,Price <CCY>,Size (qty),...".
std::vector<Row> tape_rows(const Case& c) {
    std::ifstream in(fixture(c.tape));
    CHECK(in.good());
    std::string line;
    std::getline(in, line);
    if (line.rfind("\xEF\xBB\xBF", 0) == 0) line.erase(0, 3);
    CHECK(line.rfind("Trade number,Type,Date and time,Signal,Price ", 0) == 0);
    struct Side { bool seen = false; bool is_long = true; double price = 0.0; double qty = 0.0; std::int64_t ms = 0; };
    std::map<int, std::pair<Side, Side>> by_number;  // (entry, exit)
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        const std::vector<std::string> cell = split(line, ',');
        CHECK(cell.size() >= 6);
        if (cell.size() < 6) continue;
        const int number = std::atoi(cell[0].c_str());
        const bool entry = cell[1].rfind("Entry", 0) == 0;
        CHECK(entry || cell[1].rfind("Exit", 0) == 0);
        Side& side = entry ? by_number[number].first : by_number[number].second;
        CHECK(!side.seen);
        side.seen = true;
        side.is_long = cell[1].size() >= 4 && cell[1].compare(cell[1].size() - 4, 4, "long") == 0;
        side.ms = tape_ms(cell[2]);
        side.price = std::strtod(cell[4].c_str(), nullptr);
        side.qty = std::strtod(cell[5].c_str(), nullptr);
    }
    std::vector<Row> rows;
    for (const auto& [number, pair] : by_number) {
        const Side& entry = pair.first;
        const Side& exit = pair.second;
        CHECK(entry.seen && exit.seen);
        if (!entry.seen || !exit.seen) continue;
        CHECK(entry.is_long == exit.is_long);
        rows.push_back(make_row(exit.is_long, exit.qty, entry.price, exit.price, entry.ms,
                                exit.ms, c));
    }
    return rows;
}

// The probe's script, configured from one cases.tsv row: strategy() with the
// row's initial capital and margins, 100 % of equity by default, no
// commission, no slippage; the symbol's mintick and quantity step, and for
// the stocks the exchange's time zone and regular session.
class LedgerHost final : public source::PineStrategyHost {
public:
    explicit LedgerHost(const Case& c) : c_(c) {
        attach_pine_execution_adapter();
        source::PineStrategyConfig configuration;
        configuration.initial_capital = c.capital;
        configuration.margin_long = c.margin_long;
        configuration.margin_short = c.margin_short;
        configuration.commission_type = static_cast<int>(CommissionType::PERCENT);
        configuration.commission_value = 0.0;
        configuration.slippage = 0;
        configuration.default_qty_type = static_cast<int>(QtyType::PERCENT_OF_EQUITY);
        configuration.default_qty_value = 100.0;
        configure_pine_strategy(configuration);
        set_syminfo_mintick(c.tick);
        set_syminfo_metadata("qty_step", c.step);
        if (c.symbol.rfind("NYSE:", 0) == 0 || c.symbol.rfind("NASDAQ:", 0) == 0) {
            set_syminfo_timezone("America/New_York");
            set_syminfo_session("0930-1600");
        }
        for (std::size_t index = 0; index < c_.events.size(); ++index)
            at_time_[c_.events[index].time].push_back(index);
    }

    // The calls whose time is this bar's open, in the script's statement
    // order (the plan's order); an after_close probe closes "Seed" right
    // after its boundary entry.
    void on_source_bar(const Bar& bar) override {
        const auto due = at_time_.find(bar.timestamp);
        if (due == at_time_.end()) return;
        for (const std::size_t index : due->second) {
            const Event& event = c_.events[index];
            switch (event.op) {
            case Op::Entry:
                strategy_entry(event.id, event.is_long, kNaN, kNaN, event.qty);
                break;
            case Op::Close:
                strategy_close(event.id);
                break;
            case Op::CloseAll:
                strategy_close_all();
                break;
            }
            if (event.boundary && c_.after_close) strategy_close("Seed");
        }
    }

private:
    Case c_;
    std::map<std::int64_t, std::vector<std::size_t>> at_time_;
};

struct Outcome {
    std::vector<Row> rows;
    std::string error;
};

Outcome replay(const Case& c, const std::vector<Bar>& bars) {
    LedgerHost host(c);
    host.run(bars.data(), static_cast<int>(bars.size()), c.timeframe, c.timeframe);
    Outcome outcome;
    outcome.error = host.last_error();
    // Report rows: the closed trades, then the host's range-end rows for a
    // position still open after the last bar.
    for (int index = 0; index < host.report_trade_count(); ++index) {
        const Trade& trade = host.get_report_trade(index);
        outcome.rows.push_back(make_row(trade.is_long, trade.qty, trade.entry_price,
                                        trade.exit_price, trade.entry_time, trade.exit_time, c));
    }
    return outcome;
}

std::string first_difference(const std::vector<Row>& tv, const Outcome& engine) {
    if (!engine.error.empty()) return "engine error: " + engine.error;
    const std::size_t common = std::min(tv.size(), engine.rows.size());
    std::string count;
    if (tv.size() != engine.rows.size())
        count = "rows tv=" + std::to_string(tv.size()) + " engine=" + std::to_string(engine.rows.size());
    for (std::size_t i = 0; i < common; ++i) {
        const Row& t = tv[i];
        const Row& e = engine.rows[i];
        auto field = [&](const char* name, long long expected, long long actual) {
            std::string text = "row " + std::to_string(i + 1) + " " + name + " tv=" +
                               std::to_string(expected) + " engine=" + std::to_string(actual);
            return count.empty() ? text : text + " (" + count + ")";
        };
        if (t.is_long != e.is_long) return field("long", t.is_long, e.is_long);
        if (t.qty_lots != e.qty_lots) return field("qty_lots", t.qty_lots, e.qty_lots);
        if (t.entry_ticks != e.entry_ticks) return field("entry_ticks", t.entry_ticks, e.entry_ticks);
        if (t.exit_ticks != e.exit_ticks) return field("exit_ticks", t.exit_ticks, e.exit_ticks);
        if (t.entry_ms != e.entry_ms) return field("entry_ms", t.entry_ms, e.entry_ms);
        if (t.exit_ms != e.exit_ms) return field("exit_ms", t.exit_ms, e.exit_ms);
    }
    return count;
}

// Every margin rule on. Every field of MarginRuleSwitches is named here: the
// static_assert stops the build when one is added, so it is turned on here
// too rather than left at its tree default.
pineforge::source::detail::MarginRuleSwitches all_rules_on() {
    using pineforge::source::detail::MarginRuleSwitches;
    static_assert(sizeof(MarginRuleSwitches) == 16 * sizeof(bool),
                  "MarginRuleSwitches changed: name its new field in all_rules_on() and main()");
    MarginRuleSwitches on;
    on.decimal_sizing = true;
    on.slipped_signal_admission = true;
    on.unified_placement = true;
    on.fill_price_recheck = true;
    on.close_first_admission = true;
    on.gain_loss_money = true;
    on.dust_unit_call = true;
    on.long_open_close_checks = true;
    on.negative_free_cash_call = true;
    on.coof_next_point_close = true;
    on.close_point_reversal = true;
    on.pooc_fee_sizing = true;
    on.point_fills_before_margin = true;
    on.point_order_trailing_exits = true;
    on.pyramiding_ledger_records = true;
    on.exit_child_tombstones = true;
    return on;
}

}  // namespace

int main() {
    std::printf("=== margin_ledger_rules: TradingView tapes of event-ledger margin, sizing and admission probes ===\n");
    const std::vector<Case> cases = load_cases();
    CHECK(cases.size() == kTapes);

    // The tree ships every rule on; the pass runs with the shipped switches.
    auto& switches = pineforge::source::detail::margin_rule_switches();
    const pineforge::source::detail::MarginRuleSwitches tree_defaults = switches;
    {
        const pineforge::source::detail::MarginRuleSwitches on = all_rules_on();
        CHECK(std::memcmp(&tree_defaults, &on, sizeof(on)) == 0);
    }
    CHECK(tree_defaults.decimal_sizing);
    CHECK(tree_defaults.slipped_signal_admission);
    CHECK(tree_defaults.fill_price_recheck);
    CHECK(tree_defaults.gain_loss_money);
    CHECK(tree_defaults.dust_unit_call);
    CHECK(tree_defaults.long_open_close_checks);
    CHECK(tree_defaults.negative_free_cash_call);
    CHECK(tree_defaults.coof_next_point_close);
    CHECK(tree_defaults.close_point_reversal);
    CHECK(tree_defaults.pooc_fee_sizing);

    std::map<std::string, std::string> known;
    for (const auto& [path, reason] : kKnownDivergences) {
        CHECK(!reason.empty());
        CHECK(known.emplace(path, reason).second);
    }
    std::set<std::string> listed_paths;
    std::map<std::string, std::vector<Bar>> feeds;
    // The exports of one probe (r1, r2, ...) replay the same script on the
    // same window: one engine run per probe.
    std::map<std::string, Outcome> runs;
    std::size_t matched = 0;
    std::size_t tv_rows = 0;
    for (const Case& c : cases) {
        listed_paths.insert(c.path);
        auto feed = feeds.find(c.bars);
        if (feed == feeds.end()) feed = feeds.emplace(c.bars, load_bars(c.bars)).first;
        const std::vector<Bar>& bars = feed->second;
        CHECK(!bars.empty());
        const std::vector<Row> tv = tape_rows(c);
        tv_rows += tv.size();
        auto run = runs.find(c.name);
        if (run == runs.end()) run = runs.emplace(c.name, replay(c, bars)).first;
        const std::string difference = first_difference(tv, run->second);
        const bool match = difference.empty();
        if (match) {
            ++matched;
            std::printf("MATCH %s\n", c.path.c_str());
        } else {
            std::printf("DIFF %s %s\n", c.path.c_str(), difference.c_str());
        }
        const auto listed = known.find(c.path);
        if (listed == known.end()) {
            CHECK(match);
        } else {
            // A listed tape that now matches must leave kKnownDivergences.
            CHECK(!match);
            if (match) std::printf("  now matches, remove from kKnownDivergences: %s\n", c.path.c_str());
        }
    }
    for (const auto& [path, reason] : known) CHECK(listed_paths.count(path) == 1);
    CHECK(tv_rows == kTvRows);
    std::printf("margin_ledger_rules: %zu/%zu tapes match, %zu TV rows\n", matched, cases.size(), tv_rows);

    // The admission halves, off one at a time: each costs tapes this pass
    // matched (the 104 gap-regime ledgers the fill half was pinned on, and
    // the reversal ledgers rule 2 keeps to their closing leg).
    using S = pineforge::source::detail::MarginRuleSwitches;
    const std::pair<const char*, bool S::*> halves[] = {
        {"unified_placement", &S::unified_placement},
        {"fill_price_recheck", &S::fill_price_recheck},
    };
    for (const auto& [name, flag] : halves) {
        switches = tree_defaults;
        switches.*flag = false;
        std::size_t lost = 0;
        std::map<std::string, Outcome> off_runs;
        for (const Case& c : cases) {
            if (known.count(c.path)) continue;
            auto run = off_runs.find(c.name);
            if (run == off_runs.end()) run = off_runs.emplace(c.name, replay(c, feeds.at(c.bars))).first;
            if (!first_difference(tape_rows(c), run->second).empty()) ++lost;
        }
        std::printf("ablation %s off: %zu tapes lost\n", name, lost);
        CHECK(lost > 0);
    }
    switches = tree_defaults;
    std::printf("\n%d passed, %d failed\n", tests_passed, tests_failed);
    return tests_failed ? 1 : 0;
}
