//@version=6
strategy("pf-n2r-mcr-m3", initial_capital=100875.06805, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1)
if time == timestamp("UTC", 2025, 10, 10, 14, 45)
    strategy.entry("S", strategy.short, qty=8556)
if time == timestamp("UTC", 2025, 10, 13, 13, 30)
    strategy.close("S")
if time == timestamp("UTC", 2025, 10, 13, 15, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
