//@version=6
strategy("n2b-r2-coof-low-call-on", initial_capital=4559.829648, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=0, process_orders_on_close=true, calc_on_order_fills=true)
if time == timestamp("UTC", 2025, 6, 22, 0, 0) and strategy.position_size == 0
    strategy.entry("probe", strategy.long, qty=2.0014)
if time == timestamp("UTC", 2025, 6, 22, 0, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
