//@version=6
strategy("N6B orb-may-shape", overlay=true, initial_capital=10000000, calc_on_order_fills=false, process_orders_on_close=false, pyramiding=0, margin_long=100, margin_short=100, commission_value=0, slippage=0)
inORB = hour >= 7 and hour < 8
var float orbHigh = na
var float orbLow = na
if inORB
    orbHigh := na(orbHigh) ? high : math.max(orbHigh, high)
    orbLow := na(orbLow) ? low : math.min(orbLow, low)
if bool(ta.change(time('D')))
    orbHigh := na
    orbLow := na
atr = ta.atr(14)
orbRange = orbHigh - orbLow
trail = math.max(atr * 1.5, orbRange * 0.5)
if time == timestamp("UTC",2025,5,28,17,0)
    strategy.entry('BUY', strategy.long, qty=32.0652)
if strategy.position_size > 0
    entry = strategy.position_avg_price
    sl = orbLow
    tp = entry + entry - sl
    strategy.exit('TP BUY', from_entry = 'BUY', limit = tp, qty_percent = 50, comment = "tp=" + str.tostring(tp, "0.0000000000") + " sl=" + str.tostring(sl, "0.00000000"))
    strategy.exit('RUNNER BUY', from_entry = 'BUY', trail_points = trail, stop = sl, comment = "trail=" + str.tostring(trail, "0.0000000000"))
