//@version=6
strategy("pf-16b-l16-near1", initial_capital=9792.75379, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 6, 11, 0, 30)
    strategy.entry("E", strategy.long, qty=3.5)
    strategy.exit("X", "E", stop=2797.5, limit=3226.63)
if time == timestamp("UTC", 2025, 6, 11, 1, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
