//@version=6
// SPDX-License-Identifier: Apache-2.0
// Synthetic probe (lane TAIL-H): three 0.01 lots, a 50% limit exit placed before a stop exit
strategy("tailh-d1b", overlay=true, initial_capital=100000, default_qty_type=strategy.fixed, default_qty_value=1, pyramiding=1, process_orders_on_close=true, margin_long=1, margin_short=1)
if time == timestamp("UTC", 2025, 10, 21, 8, 45)
    strategy.entry("L", strategy.long, qty=0.03)
    strategy.exit("TP1_L", from_entry="L", qty_percent=50, limit=4331.72)
    strategy.exit("MAIN_L", from_entry="L", stop=4245.365, limit=4389.29)
