//@version=6
strategy("pf-n2s-e2-long-resid-nocall", initial_capital=101126.7204476765, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 7, 27, 19, 30)
    strategy.entry("L", strategy.long, qty=26.3713)
if time == timestamp("UTC", 2025, 7, 27, 19, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
