//@version=6
strategy("pf-16b-s16-unit", initial_capital=15669.757261, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 9, 21, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=4478.35, limit=3800.88)
if time == timestamp("UTC", 2025, 9, 21, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
