//@version=6
strategy("pf-recheck-c1-recheck-no-l-s1g3", initial_capital=93848.8463, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 7, 8, 18, 45)
    strategy.entry("S", strategy.short, qty=80000.0)
if time == timestamp("UTC", 2025, 7, 8, 19, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
