//@version=6
strategy("pf-16b-s16-pct-stop", initial_capital=10000.0, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 4, 2, 0, 15)
    strategy.entry("E", strategy.short)
    strategy.exit("X", "E", stop=1898.49, limit=1607.07)
if time == timestamp("UTC", 2025, 4, 2, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
