//@version=6
strategy("n12-c1-c-exp-long-m50-under", initial_capital=1898.2724999999998, margin_long=50, margin_short=50, commission_type=strategy.commission.percent, commission_value=0.0, slippage=0, process_orders_on_close=false, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 5, 21, 12, 0) and strategy.position_size == 0
    strategy.entry("probe", strategy.long, qty=1.5)
if time == timestamp("UTC", 2025, 5, 21, 12, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
