//@version=6
strategy("n12-c1-a3-exp-long-s1-gapup1", initial_capital=3772.455001, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=1, process_orders_on_close=false, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 5, 20, 11, 30) and strategy.position_size == 0
    strategy.entry("probe", strategy.long, qty=1.5)
if time == timestamp("UTC", 2025, 5, 20, 12, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
