//@version=6
strategy("n12-c1-a2-pct-short-s2-gapup1", initial_capital=5076.400001000001, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=2, process_orders_on_close=false, calc_on_order_fills=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
if time == timestamp("UTC", 2025, 5, 20, 6, 15) and strategy.position_size == 0
    strategy.entry("probe", strategy.short)
if time == timestamp("UTC", 2025, 5, 20, 6, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
