//@version=6
strategy("pf-recheck-b2-recheck-owes-s2g4", initial_capital=94048.3255, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 7, 3, 18, 30)
    strategy.entry("S", strategy.short, qty=80000.0)
if time == timestamp("UTC", 2025, 7, 3, 18, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
