//@version=6
strategy("n5b-13-apex-third",initial_capital=5000,pyramiding=10,margin_long=1,margin_short=1,close_entries_rule="FIFO",commission_type=strategy.commission.percent,commission_value=0.05)
if time == timestamp("UTC",2025,7,30,6,0,0)
    strategy.entry("Long",strategy.long,qty=2164.89)
if strategy.position_size > 0
    strategy.exit("Wick_Exit_L",stop=0.9,limit=1.3)
if time == timestamp("UTC",2025,7,31,10,30,0)
    strategy.entry("Long_Add",strategy.long,qty=4374.3)
if time == timestamp("UTC",2025,8,1,12,15,0)
    strategy.entry("Long_Add",strategy.long,qty=8771.85)
if time == timestamp("UTC",2025,8,1,12,45,0)
    strategy.exit("Wick_Exit_L",stop=1.15439,limit=1.3)
if time == timestamp("UTC",2025,8,1,16,0,0)
    strategy.close_all()
