//@version=6
strategy("N6B xau-trailpts-1000p000003", overlay=true, initial_capital=10000000, calc_on_order_fills=false, process_orders_on_close=false, pyramiding=0, margin_long=100, margin_short=100, commission_value=0, slippage=0)
if time == timestamp("UTC",2025,6,12,6,0)
    strategy.entry("BUY", strategy.long, qty=10)
if strategy.position_size > 0
    strategy.exit("RUNNER BUY", "BUY", trail_points=1000.000003, stop=3300.0)
if time >= timestamp("UTC",2025,6,12,20,0)
    strategy.close_all(comment="cleanup")
