//@version=6
strategy("pf-n2s-a4-short-gap", initial_capital=68117.44643333332, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 5, 30, 20, 45)
    strategy.entry("S", strategy.short, qty=60000.0)
if time == timestamp("UTC", 2025, 6, 1, 21, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
