//@version=6
strategy("n2b-r3-close-point-nonclose-bar", initial_capital=9951.927628, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=0, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 5, 23, 4, 30) and strategy.position_size == 0
    strategy.entry("probe", strategy.long, qty=3.7083)
if time == timestamp("UTC", 2025, 5, 23, 5, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
