//@version=6
strategy("N1B flat-eth-fillexact-under", initial_capital=10762.945689999999, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2026, 2, 2, 2, 0)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################")
    strategy.entry("Turn", strategy.long, comment=witness)
if time == timestamp("UTC", 2026, 2, 2, 2, 45)
    strategy.close_all(comment="SENSOR|" + witness)
