//@version=6
strategy("pf-n2s-e4-adm-short-ok", initial_capital=8443.24, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 8, 20, 9, 15)
    strategy.entry("S", strategy.short, qty=2.0)
if time == timestamp("UTC", 2025, 8, 20, 10, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
