//@version=6
strategy("pf-n2s-r12-long-0429", initial_capital=85037.49303811882, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 4, 29, 22, 0)
    strategy.entry("L", strategy.long, qty=74663.45)
if time == timestamp("UTC", 2025, 4, 30, 0, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
