//@version=6
strategy("pf-16b-s16-at-open", initial_capital=7129.78335, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2026, 3, 11, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=2036.77, limit=1721.68)
if time == timestamp("UTC", 2026, 3, 11, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
