//@version=6
strategy("pxsame-S-t-lim-nc", overlay=true, initial_capital=1000000, default_qty_type=strategy.fixed, default_qty_value=1, pyramiding=2, calc_on_order_fills=false, process_orders_on_close=false)
if strategy.position_size == 0
    strategy.cancel("A")
    strategy.entry("H", strategy.short, qty=1)
else if strategy.position_size < 0
    strategy.entry("A", strategy.short, qty=1, limit=100.0)
    strategy.exit("X", trail_points=5, trail_offset=2)
