//@version=6
strategy("pf-16b-s16-near1", initial_capital=7584.91836, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2026, 3, 26, 0, 30)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=2166.8, limit=1836.19)
if time == timestamp("UTC", 2026, 3, 26, 1, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
