//@version=6
strategy("pf-16b-s16-partial", initial_capital=13442.900095, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 11, 1, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", qty=1.75, stop=3840.79, limit=3256.07)
if time == timestamp("UTC", 2025, 11, 1, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
