//@version=6
strategy("pf-recheck-r0-cohort-0618", initial_capital=91576.806101, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 6, 18, 18, 45)
    strategy.entry("S", strategy.short, qty=79764.22)
if time == timestamp("UTC", 2025, 6, 18, 19, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
