//@version=6
strategy("rt-ls-stop-down-pooc", initial_capital=99962.09, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 4, 29, 14, 0)
    strategy.entry("Long", strategy.long, qty=950)
    strategy.exit("Exit Long", from_entry="Long", stop=9.0)
if time == timestamp("UTC", 2025, 4, 29, 14, 45)
    strategy.entry("Short", strategy.short)
if time == timestamp("UTC", 2025, 4, 29, 15, 0)
    strategy.close_all()
