//@version=6
strategy("n2b-r2-admit-eur-short-nonpooc-s1-ulp", initial_capital=106575.300002, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=1, process_orders_on_close=false, calc_on_order_fills=false)
if time == timestamp("UTC", 2026, 2, 17, 3, 45) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=90000.0)
if time == timestamp("UTC", 2026, 2, 17, 4, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
