//@version=6
strategy("pf-n2s-a5-owed-dropped-eur", initial_capital=70446.5062, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 10, 1, 23, 0)
    strategy.entry("S", strategy.short, qty=60000.0)
if time == timestamp("UTC", 2025, 10, 1, 23, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
