//@version=6
strategy("N6 independent orb-july-fresh", overlay=true, initial_capital=10000000, calc_on_order_fills=false, process_orders_on_close=false, pyramiding=0, margin_long=100, margin_short=100, commission_value=0, slippage=0)
if time == timestamp("UTC",2025,7,15,12,45)
    strategy.entry("ticket", strategy.long, qty=27.0262)
if strategy.position_size > 0
    strategy.exit("target", "ticket", limit=3026.99, qty_percent=50)
    strategy.exit("runner", "ticket", trail_points=10.0, stop=2971.81)
