//@version=6
strategy("pf-16b-s16-noslip", initial_capital=15304.53605, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 9, 1, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=4385.81, limit=3700.79)
if time == timestamp("UTC", 2025, 9, 1, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
