//@version=6
strategy("Full margin batch and opening fees", initial_capital=2733, pyramiding=3, default_qty_type=strategy.fixed, default_qty_value=1, margin_long=100, margin_short=100, commission_type=strategy.commission.cash_per_contract, commission_value=1)
if time == timestamp("UTC", 2025, 4, 1, 0, 0)
    strategy.entry("A", strategy.short, qty=0.5)
    strategy.entry("B", strategy.short, qty=0.5)
    strategy.entry("C", strategy.short, qty=0.5)
if time == timestamp("UTC", 2025, 4, 1, 6, 0)
    strategy.close_all()
