//@version=6
strategy("N1B gap-G2-long-to-short-gap+0", initial_capital=96643.429999999993, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2026, 2, 2, 18, 15)
    strategy.entry("Seed", strategy.long, qty=7000)
if time == timestamp("UTC", 2026, 2, 2, 18, 45)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################")
    strategy.entry("Turn", strategy.short, comment=witness)
if time == timestamp("UTC", 2026, 2, 2, 19, 30)
    strategy.close_all(comment="SENSOR|" + witness)
