//@version=6
strategy("Batch entries with pending cancellation", initial_capital=1000000, pyramiding=3, default_qty_type=strategy.fixed, default_qty_value=1, margin_long=0, margin_short=0)
if time == timestamp("UTC", 2025, 4, 1, 0, 0)
    strategy.entry("A", strategy.long, qty=1)
    strategy.entry("B", strategy.long, qty=2)
    strategy.entry("C", strategy.long, qty=3)
    strategy.cancel("B")
if time == timestamp("UTC", 2025, 4, 1, 6, 0)
    strategy.close_all()
