//@version=6
strategy("Margin market short cash", initial_capital=100000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, commission_type=strategy.commission.cash_per_contract, commission_value=0.25, pyramiding=0)
var int counter = 0
if time >= timestamp("UTC", 2025, 5, 12, 0, 0)
    counter += 1
if counter == 1
    strategy.entry("seed", strategy.long)
if counter == 12
    strategy.entry("test", strategy.short)
if counter == 24
    strategy.cancel_all()
    strategy.close_all()
plot(strategy.equity)
