//@version=6
strategy("n2-stopband-stop-p100u", initial_capital=98476.49582020029, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0, slippage=0, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2026, 2, 17, 15, 15) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=83397.41, stop=1.18081)
if time == timestamp("UTC", 2026, 2, 17, 17, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
plot(math.floor(strategy.equity / close / 0.01) * 0.01, "source-size")
