//@version=6
strategy("n2b-r2-size-eur-02-17-t1", initial_capital=99999.416373, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=0, process_orders_on_close=true, calc_on_order_fills=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
if time == timestamp("UTC", 2026, 2, 17, 3, 15) and strategy.position_size == 0
    strategy.entry("probe", strategy.long)
if time == timestamp("UTC", 2026, 2, 17, 3, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
