//@version=6
strategy("n2c-feesize-eth-short-s0-f5-m2em05", initial_capital=53246.1369436, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=true)
if time == timestamp("UTC", 2026, 1, 8, 23, 30)
    strategy.entry("after", strategy.short)
if time == timestamp("UTC", 2026, 1, 9, 1, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "position")
