//@version=6
strategy("pf-16b-l16-gaplim", initial_capital=8855.564925, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 5, 21, 0, 15)
    strategy.entry("E", strategy.long, qty=3.5)
    strategy.exit("X", "E", stop=2140.54, limit=2529.75)
if time == timestamp("UTC", 2025, 5, 21, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
