//@version=6
strategy("pf-n2s-e5-adm-long-drop", initial_capital=8443.28, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 8, 20, 9, 15)
    strategy.entry("L", strategy.long, qty=2.0)
if time == timestamp("UTC", 2025, 8, 20, 10, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
