//@version=6
strategy("pf-16b-s16-gap-tiny", initial_capital=5632.234445, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 4, 21, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", qty=0.0004, stop=1608.93, limit=1364.83)
if time == timestamp("UTC", 2025, 4, 21, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
