//@version=6
strategy("n5b-02-tie-qa",initial_capital=500000,pyramiding=20,margin_long=0,margin_short=0,close_entries_rule="ANY")
if time == timestamp("UTC",2025,7,30,6,0,0)
    strategy.entry("Q",strategy.long,qty=3)
if strategy.position_size > 0
    strategy.exit("Wick",stop=0.9,limit=1.3)
if time == timestamp("UTC",2025,7,31,10,30,0)
    strategy.entry("A",strategy.long,qty=7)
if time == timestamp("UTC",2025,8,1,12,30,0)
    strategy.exit("Wick",stop=0.9,limit=1.15439)
if time == timestamp("UTC",2025,8,1,16,0,0)
    strategy.close_all()
