//@version=6
strategy("N1B gap-G5-short-to-long-gap+0", initial_capital=96715.039999999994, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2026, 2, 3, 17, 0)
    strategy.entry("Seed", strategy.short, qty=7000)
if time == timestamp("UTC", 2026, 2, 3, 17, 30)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################")
    strategy.entry("Turn", strategy.long, comment=witness)
if time == timestamp("UTC", 2026, 2, 3, 18, 15)
    strategy.close_all(comment="SENSOR|" + witness)
