//@version=6
strategy("pf-n2r-ck-l2", initial_capital=68409.01899798999, pyramiding=2, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 4, 18, 13, 15)
    strategy.entry("A", strategy.short, qty=2.0)
if time == timestamp("UTC", 2025, 4, 18, 13, 45)
    strategy.entry("B", strategy.short, qty=60000.0)
if time == timestamp("UTC", 2025, 4, 18, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
