//@version=6
strategy("N1B flat-aapl-below-equal", initial_capital=104617.71000000001, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2026, 1, 5, 15, 0)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################")
    strategy.entry("Turn", strategy.long, comment=witness)
if time == timestamp("UTC", 2026, 1, 5, 15, 45)
    strategy.close_all(comment="SENSOR|" + witness)
