//@version=6
strategy("pf-n2s-r05-0227", initial_capital=6772.062540000002, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2026, 2, 27, 15, 0)
    strategy.entry("S", strategy.short, qty=472.0)
if time == timestamp("UTC", 2026, 2, 27, 16, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
