//@version=6
strategy("pf-16b-s16-limit", initial_capital=13050.03898, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 7, 21, 0, 30)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=4306.06, limit=3724.52)
if time == timestamp("UTC", 2025, 7, 21, 1, 15)
    strategy.close_all()
plot(strategy.equity, "equity")
