//@version=6
strategy("pf-recheck-b3-recheck-owes-low-s2g4", initial_capital=91432.6228, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 7, 31, 4, 15)
    strategy.entry("S", strategy.short, qty=80000.0)
if time == timestamp("UTC", 2025, 7, 31, 4, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
