//@version=6
strategy("pf-16b-f-stop2", initial_capital=19125.655, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 4, 7, 14, 0)
    strategy.entry("E", strategy.short, qty=2000)
    strategy.exit("X", "E", stop=9.6, limit=7.73)
if time == timestamp("UTC", 2025, 4, 7, 14, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
