//@version=6
strategy("pf-n2s-e3-short-nongap", initial_capital=132704.43420000002, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 8, 15, 22, 15)
    strategy.entry("S", strategy.short, qty=30.0)
if time == timestamp("UTC", 2025, 8, 15, 22, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
