//@version=6
strategy("N1 roi-k0-above-after", initial_capital=86906.750000000015, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100)
var string witness = ""
if time == timestamp("UTC", 2025, 9, 19, 13, 30)
    strategy.entry("Seed", strategy.short, qty=5693)
if time == timestamp("UTC", 2025, 10, 1, 13, 30)
    witness := "E=" + str.tostring(strategy.equity, "#.################") + ";N=" + str.tostring(strategy.netprofit, "#.################") + ";OP=" + str.tostring(strategy.openprofit, "#.################") + ";P=" + str.tostring(strategy.position_size, "#.################") + ";C=" + str.tostring(close, "#.################") + ";T=" + str.tostring(math.round_to_mintick(close), "#.################") + ";D=" + str.tostring(strategy.default_entry_qty(math.round_to_mintick(close)), "#.################")
    strategy.entry("Turn", strategy.long, comment=witness)
    strategy.close("Seed")
if time == timestamp("UTC", 2025, 10, 3, 13, 30)
    strategy.close_all(comment="SENSOR|" + witness)
