//@version=6
strategy("n2b-r2-size-eth-05-23-t2", initial_capital=39992.847663, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.0, slippage=0, process_orders_on_close=false, calc_on_order_fills=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
if time == timestamp("UTC", 2025, 5, 23, 0, 15) and strategy.position_size == 0
    strategy.entry("probe", strategy.long)
if time == timestamp("UTC", 2025, 5, 23, 0, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
