//@version=6
strategy("pf-f5-l-path", initial_capital=11029.83049, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2026, 1, 5, 0, 15)
    strategy.exit("X", stop=3146.67, limit=3627.52)
    strategy.entry("E", strategy.long, qty=3.5)
if time == timestamp("UTC", 2026, 1, 5, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
