//@version=6
strategy("pf-n2r-ck-g5", initial_capital=28517.958249999996, default_qty_type=strategy.percent_of_equity, default_qty_value=100, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.1, slippage=3, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 4, 18, 13, 45)
    strategy.entry("probe", strategy.short, qty=25000.0)
if time == timestamp("UTC", 2025, 4, 18, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
