//@version=6
strategy("n2-member-13-literal", initial_capital=97047.53842489024, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 4, 12, 23, 0) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=1.1383400000000001)
if time == timestamp("UTC", 2025, 4, 13, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
plot(math.floor(strategy.equity / close / 0.00001) * 0.00001, "source-size")
