//@version=6
strategy("n2-member-21-literal", initial_capital=8801.038430000006, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=true, calc_on_order_fills=false)
if time == timestamp("UTC", 2025, 9, 17, 19, 0) and strategy.position_size == 0
    strategy.entry("probe", strategy.short, qty=758)
if time == timestamp("UTC", 2025, 9, 17, 19, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
plot(strategy.position_size, "held")
plot(strategy.netprofit, "netprofit")
plot(strategy.openprofit, "openprofit")
plot(math.floor(strategy.equity / close / 1) * 1, "source-size")
