//@version=6
strategy("pf-12b-c2-two-shorts", initial_capital=700027.3682, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true, pyramiding=2)
if time == timestamp("UTC", 2026, 4, 9, 1, 45)
    strategy.entry("A", strategy.short, qty=20.0)
    strategy.entry("B", strategy.short, qty=600000.37)
if time == timestamp("UTC", 2026, 4, 9, 2, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
