//@version=6
strategy("pf-n2s-r19-resize-0602", initial_capital=75618.548318831, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 6, 2, 3, 30)
    strategy.entry("S", strategy.short, qty=30.262)
if time == timestamp("UTC", 2025, 6, 2, 5, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
