//@version=6
strategy("pf-16b-ab-e-exact", initial_capital=5524.90294, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.1, slippage=0, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 4, 20, 14, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=1579.74)
if time == timestamp("UTC", 2025, 4, 20, 15, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
