//@version=6
strategy("pf-16b-s16-gap-noslip", initial_capital=9912.960935, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=false)
if time == timestamp("UTC", 2026, 1, 26, 0, 15)
    strategy.entry("E", strategy.short, qty=3.5)
    strategy.exit("X", "E", stop=2831.84, limit=2398.63)
if time == timestamp("UTC", 2026, 1, 26, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
