//@version=6
strategy("margin-lag-close", initial_capital=68405, pyramiding=2, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=0, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 4, 18, 13, 0)
    strategy.entry("A", strategy.short, qty=0.5)
if time == timestamp("UTC", 2025, 4, 18, 13, 30)
    strategy.entry("B", strategy.short, qty=60000.0)
if time == timestamp("UTC", 2025, 4, 18, 14, 30)
    strategy.close_all()
plot(strategy.equity, "equity")
