//@version=6
strategy("pf-recheck-e1-eth-recheck-owes-s1g3", initial_capital=764998.53, margin_long=100, margin_short=100, commission_type=strategy.commission.percent, commission_value=0.05, slippage=1, process_orders_on_close=true)
if time == timestamp("UTC", 2025, 6, 17, 13, 30)
    strategy.entry("S", strategy.short, qty=300.0)
if time == timestamp("UTC", 2025, 6, 17, 13, 45)
    strategy.close_all()
plot(strategy.equity, "equity")
