//@version=6
strategy("pxsame2-S-p-rstp-nc", overlay=true, initial_capital=1000000, default_qty_type=strategy.fixed, default_qty_value=1, pyramiding=2, calc_on_order_fills=false, process_orders_on_close=false)
var bool placed = false
if strategy.position_size == 0
    strategy.cancel("A")
    placed := false
    strategy.entry("H", strategy.short, qty=1)
else if strategy.position_size < 0
    if not placed
        strategy.entry("A", strategy.short, qty=1, stop=strategy.position_avg_price - 0.03)
        placed := true
    strategy.exit("X", profit=4)
