//@version=6
strategy("pf-16b-s16-lev50", initial_capital=13023.058547, margin_long=50, margin_short=50, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, process_orders_on_close=false)
if time == timestamp("UTC", 2025, 10, 12, 0, 15)
    strategy.entry("E", strategy.short, qty=7.0)
    strategy.exit("X", "E", stop=3740.29, limit=3159.8)
if time == timestamp("UTC", 2025, 10, 12, 1, 0)
    strategy.close_all()
plot(strategy.equity, "equity")
